### ISSUE TITLE
doens't handle git commit callback properly

### ISSUE THREAD

**Issue by e-cloud** [conventional-changelog/standard-version#108]
I have a git hook to check code style before commit(using *eslint*). If my code has error style, commit will not continue. If only have warnings, they will be shown, but commit can continue.

now `standard-version` will perform a release commit, which will also trigger the git hook.

However, it treat all `stderr` as illegal and just exit without continuing to perform `git tag`.

see [the code](https://github.com/conventional-changelog/standard-version/blob/master/index.js#L123)

i think it should either prevent the git hooks when committing or improve the error handler

**Comment by stevemao** [comment]
duplicate of https://github.com/conventional-changelog/standard-version/issues/91?

**Comment by e-cloud** [comment]
looks like you are right
