### ISSUE TITLE
RC Support

### ISSUE THREAD

**Issue by DxCx** [conventional-changelog/standard-version#109]
Hi,

i thought about it and i think that there is a need to define an RC release,
so for example, after the next version calculation, it will append -rc.1 to it,
if rc.1 exists it will incremeant the number.
and then once standard-version is run without the --rc keyword it will release the real version that suppose to to be released.

thoughts?

**Comment by Tapppi** [comment]
Duplicate of #83, complain and reopen if I got it wrong.

**Comment by DxCx** [comment]
Yep you are correct that will do, didnt got the context when reading subjects..

Thanks!
