### ISSUE TITLE
allow any added files to be committed

### ISSUE THREAD

**Issue by benmonro** [conventional-changelog/standard-version#119]
currently `npm version` will do a commit which includes any staged files.  This is useful in our scenario where we have additional files that our build needs to commit, in addition to the changelog and package.json.  It would be nice if standard-version worked this way and/or allowed us to do the commit ourselves.

**Comment by benmonro** [comment]
as it stands each build is now doing 2 additional commits, 1 for the standard-version affected files and another for the additional files we need to commit.

**Comment by Tapppi** [comment]
Closed by #121
