### ISSUE TITLE
detect breaking changes anywhere

### ISSUE THREAD

**Issue by benmonro** [conventional-changelog/standard-version#120]
currently the docs are a bit misleading.  They say if there are any "BREAKING CHANGES" it will appear in the change log (and thus bump the major version).

![image](https://cloud.githubusercontent.com/assets/399236/19134180/53c388a4-8b11-11e6-9694-74525fe54bd3.png)

This verbiage is confusing as people on our team are making their commit messages something like  `BREAKING CHANGE: removed deprecated component` expecting it to bump the major version etc when the commit is part of a squash.  The problem is that the squash is adding an asterisk at the beginning of that message and standard-version isn't picking it up.

It seems to me that if the pattern `BREAKING CHANGE: ` is found anywhere in the commit message it should trigger a major version bump and change log update....

**Comment by stevemao** [comment]
@benmonro Feel free to submit a PR and change it :)

**Comment by benmonro** [comment]
@stevemao https://github.com/conventional-changelog/conventional-commits-parser/pull/31 :)

**Comment by stevemao** [comment]
Moving discussion there.
