### ISSUE TITLE
CHANGELOG entries added multiple times

### ISSUE THREAD

**Issue by bcoe** [conventional-changelog/standard-version#123]
I continue to occasionally create a scenario where changes are added to the CHANGELOG multiple times, across multiple releases:

https://github.com/conventional-changelog/standard-version/commit/1727ea8be0d94016291059ea04dc5288cacf0b67

I think we should dig into the root cause of this, and make it harder to cause. My hunch is that it's related to releasing a candidate release off of a branch; once that branch is merged, I would expect the history to be properly resolved without duplicates.

CC: @Tapppi, @stevemao

**Comment by bcoe** [comment]
@Tapppi I've been swayed by the argument that we should only generate CHANGELOGs from the `master` branch, should I close this do you think?

**Comment by Tapppi** [comment]
@bcoe see my comment in https://github.com/conventional-changelog/git-semver-tags/pull/10#issuecomment-264289110. I think its fine to close this, or keep it open to track if we want to enable this option at some point (if it becomes stable and preferable)?

**Comment by bcoe** [comment]
@Tapppi let's keep it open as a tracking ticket for the time being; if nothing else, it reminds me to update that other ticket with a configuration flag.

**Comment by Tapppi** [comment]
Maybe change the labels accordingly? I don't think this is exactly a bug as much as a workflow restriction. :smile:

**Comment by redreceipt** [comment]
So what's the resolution here? I can't use a `release` branch to PR into the base?

**Comment by ldanielw1** [comment]
want to ask if there's been a resolution on this? We recently moved to naming our branches `main` because we're feeling uncomfortable with the name `master` - but am wondering if this is why we're now experiencing issues?
