### ISSUE TITLE
How to increment versions starting from 0.0.1 ?

### ISSUE THREAD

**Issue by helio-frota** [conventional-changelog/standard-version#132]
Hi,
I'm starting a project using 0.0.1 as default on my package.json.
When I publish, it goes to 1.0.0.
Any tips how to publish 0.0.1 ? 
thanks.

**Comment by stevemao** [comment]
duplicate of https://github.com/conventional-changelog/standard-version/issues/131?

**Comment by helio-frota** [comment]
almost duplicated.

**Comment by stevemao** [comment]
What's the difference?

**Comment by helio-frota** [comment]
From the issue 131:
> So upgrade a minor number only if there is a breaking change. 

For example, currently I'm working on a project at version: 0.13.0
I have plan to migrate the design, and it will change the API [ a new API incompatible, breaking ], so this will go to 1.0.0, not 0.14.0.

> MAJOR version when you make incompatible API changes,
> MINOR version when you add functionality in a backwards-compatible manner, and
> PATCH version when you make backwards-compatible bug fixes.
(http://semver.org/)

**Comment by helio-frota** [comment]
@stevemao Hi,

Sorry this was my fault.
I did a `breaking` change, but was thinking on `minor` change.
[ due quick experiment on this project]

I tested again with more attention, this is working fine.
Thanks.
