### ISSUE TITLE
support pre-patch

### ISSUE THREAD

**Issue by benmonro** [conventional-changelog/standard-version#133]
we are interested in having a pre-release cycle which publishes prepatch versions of our builds.  We'd like to keep using standard-version for that, but we noticed there's no support for  pre-patch versions in standard-version.  Was this intentional and if so why?

**Comment by Tapppi** [comment]
This is in the works. PR's #83 #129 and the issue for it generally is #122. It's not as simple as one might think, but I'll try to get to pushing it forward asap. Paid work takes time unfortunately.. Closing as duplicate, holla at me if you disagree.
