### ISSUE TITLE
Do nothing if no valid commits?

### ISSUE THREAD

**Issue by tleunen** [conventional-changelog/standard-version#136]
Would it make sense, or is it out of scope, to not change the version of a package if there're no valid commits between the HEAD and the last version?

Only valid commits that I see would be `fix`, `feat`, `perf` and `revert`?

**Comment by bcoe** [comment]
@tleunen I think it might be out of scope, there are definitely scenarios where a commit lands on a repo, e.g., `docs: updated help`, or `chore: update dependency version` where you want to release a new package version, but it doesn't fall within the DSL used by the conventional commit format.

I think the default behavior of a patch bump works well for this, and it falls more on the library maintainers shoulders to decide whether or not these releases are appropriate.
