### ISSUE TITLE
Inconsistent handling of merge commits

### ISSUE THREAD

**Issue by dsole** [conventional-changelog/standard-version#137]
I noticed today that the "semver version increment type" calculation and the change log generation  are inconsistent in their handling of merge commits 
A merge commit with a message that meets the convention,

- IS considered when calculating the version increment type
- IS NOT included in the changelog.

It makes sense to me that they should be consistent - either merges are included or they aren't. My preference is that they _are_ considered as I would like the merge commit to follow the convention but I'm not concerned about whether the commits in the child branch follow the convention.

Essentially this git history shows a feature branch that is then merged back into master.
In the branch I made commit 9b9ba5 ("making a change") and then merged that branch to the master branch in commit 37cdce ("feat(index): Add new feature").  Pretend that the branch contained multiple commits and that FF wasn't possible.

```
$ git log --graph

*   commit 37cdce8d34b15113ba7aae399994ba6c85c0f673
| \  Merge: 0b68b0c 9b9ba57
|   | Author: dsole
|   | Date:   Fri Nov 11 14:30:57 2016 +1100
|   |
|   |     feat(index): Add new feature
|   |
|   * commit 9b9ba57f31231fa8005fcfd38895adc32a88591d
| /   Author: dsole
|     Date:   Fri Nov 11 14:29:34 2016 +1100
|
|        making a change
|
* commit 0b68b0c612cbd5783688120744a00b9a01c2c2af
| Author: dsole
| Date:   Fri Nov 11 14:28:13 2016 +1100
|
|     chore(release): 1.0.0
|
* commit 954708674b659b3b53fdc405acf2afcba37d0e9b
  Author: dsole
  Date:   Fri Nov 11 14:27:04 2016 +1100

      feat(index): Add some files
```

At this point when I run `standard-version`, the version is incremented to 1.1 because the feat() commit was detected. But the feature was not added to the changelog.
This commit is created:

```
commit 994c7499e212e44f66de73d11d95ab9ee49f7833  
Author: dsole
Date:   Fri Nov 11 14:32:53 2016 +1100           
                                                 
    chore(release): 1.1.0                        
```                                                 
and the changelog:
```
# Change Log

All notable changes to this project will be documented in this file. See [standard-version](https://github.com/conventional-changelog/standard-version) for commit guidelines.

<a name="1.1.0"></a>
# [1.1.0](/compare/v1.0.0...v1.1.0) (2016-11-11)



<a name="1.0.0"></a>
# 1.0.0 (2016-11-11)


### Features

* **index:** Add some files 9547086
```

Expected result:
The version is incremented to 1.1.0 and the changelog contains the new "Add new feature" feature.

Justification:
If you consider that the branch may contain multiple iterations of the work (this is a single central repo pattern not a forked repo pattern, so its more likely to have multiple, non-squashed commits) then I don't want each of those individual changes to identify the feature in their message - I'd want one single commit that follows the feat() convention to describe the overall new feature, and that would be the merge commit.

What are your thoughts on including merge changes in the changelog ?
I had a quick look - hopefully it might be configurable by passing options to conventionalChangelog() but perhaps the behaviour is baked into the conventional-changelog package.

**Comment by stevemao** [comment]
Regardless whether we should write special messages in the merge commits, I'm happy to include them when generating the CHANGELOG. I don't think there is downside except it might be a bit slower?
That said, I don't know if it's a good idea to include a `feat` in the merge commits. Maybe a merge commit could use a subject like `merge` (I might do that if there's any conflict)? But more commonly it's rebased onto the target branch (See the angular repos).

**Comment by stevemao** [comment]
I don't think it's a big issue including them 
@dsole you are right, there is already an option. PR welcome. Unless there's objection this should be fine :)
