### ISSUE TITLE
compare link is not correct for bitbucket

### ISSUE THREAD

**Issue by hanks** [conventional-changelog/standard-version#142]
I use angular template, and the link created seems to be github version, and like below:

`https://bitbucket.org/user/repo/compare/v0.1.0...v0.2.0`

but the right url would be:

`https://bitbucket.org/user/repo/branches/compare/v0.2.0%0Dv0.1.0`

Is this can be configured?

**Comment by stevemao** [comment]
Please join https://github.com/conventional-changelog/conventional-changelog-core/pull/21 for discussion.

**Comment by hanks** [comment]
thx

**Comment by stevemao** [comment]
I'm happy to keep this open for visibility.

**Comment by enriquecaballero** [comment]
@hanks Neither of those two links work for me. I've tried two dots, triple dots, and using %0D. No dice. Running BitBucket Server 4.14.4.

**Comment by enriquecaballero** [comment]
Would love to have links be configurable. Don't even know how we're going to get around linking our issues to JIRA.

**Comment by enriquecaballero** [comment]
The base URL up to `../compare/` works for me, but the triple dot syntax just takes me to a dead link page.

**Comment by bcoe** [comment]
@hanks @enriquecaballero as of `standard-version@6.0.0` you can now set the variable `compareUrlFormat` in a `.versionrc`, and correct the URL format for a given platform.

Let me know if this does the trick for you.
