### ISSUE TITLE
Support for tag signing

### ISSUE THREAD

**Issue by Conaclos** [conventional-changelog/standard-version#15]
Hi! Very nice project!

I'm currently signing my tags (`git tag -s`).
It could be nice to add an option to enforce tag signing.
Similar to the npm's option `sign-git-tag`.

**Comment by bcoe** [comment]
@Conaclos this sounds like a great addition \o/ would you like to take a stab at adding it?

The unit tests are pretty easy to write, they're simply git integration tests.

**Comment by Conaclos** [comment]
Sorry, what's a **stab**?

After a bit of investigation, I found the addition of a new feature in the coming release of Git.

I wrote more details about it in #18.
Although the PR is ridiculously little, it makes **standard-version** ready for Git 2.9 ;)

**Comment by bcoe** [comment]
@Conaclos `stab` is a saying meaning basically "attempt to implement". 

I think it would be nice to have this added as a command line option, I'll comment on the pull.

**Comment by nexdrew** [comment]
@Conaclos Give `standard-version@2.2.1` a try and let us know if you have any trouble with the new `--sign` option. And thanks for your contributions!
