### ISSUE TITLE
Github Enterprise URL's are being made plural

### ISSUE THREAD

**Issue by patrickmichalina** [conventional-changelog/standard-version#151]
It is generating an extra "s" on the commit portion of the uri. When clicking, it shows ALL commits. No very useful, I want to see commit/#hash. Any reason the system would be doing this? I don't see it happening in this repo's changelog

Ex:
https:/github.com/thinger/thingy/commits/g762af5

**Comment by bcoe** [comment]
@patrickmichalina this definitely doesn't sound right! would love the help digging into this if you have the time otherwise hopefully myself, @Tapppi, or one of the other core maintainers will have a chance to look soon.

**Comment by Tapppi** [comment]
@bcoe I tried to scour https://github.com/conventional-changelog/conventional-changelog-angular and https://github.com/conventional-changelog/conventional-changelog-core a bit but couldn't find anything that would cause this.. github has only `commit: 'commit'` as the host commit ref.  @patrickmichalina any chance you have an example that can reproduce this?

**Comment by bcoe** [comment]
@patrickmichalina a failing test would kick butt 👍 would help us get this patched ASAP.

**Comment by patrickmichalina** [comment]
@bcoe I am new to this tooling and wondering if re-based or merged commits could be doing this? I will try to see if I can find out more information about why this might be happening.

**Comment by patrickmichalina** [comment]
@Tapppi the only thing with "commits" in those repos is for this test:

```javascript
it('should work with unknown host', function(done) {
    preparing(7);
    var i = 0;

    conventionalChangelogCore({
      config: preset,
      pkg: {
        path: __dirname + '/fixtures/_unknown-host.json'
      }
    })
      .on('error', function(err) {
        done(err);
      })
      .pipe(through(function(chunk, enc, cb) {
        chunk = chunk.toString();

        expect(chunk).to.include('(http://unknown/compare');
        expect(chunk).to.include('](http://unknown/commits/');

        i++;
        cb();
      }, function() {
        expect(i).to.equal(1);
        done();
      }));
  });
```

this line 

```javascript
expect(chunk).to.include('](http://unknown/commits/');
```

Haven't dug deep, but the name of the test might mean "if not github.com". Not sure why that would matter though. But this may be specific to github enterprise (which is where this is happening!). I checked another private repo for a github.com hosted app an it doesn't appear to be happening.

**Comment by Tapppi** [comment]
Ah, thank you for the clarification about github enterprise @patrickmichalina, I was just going to ask what host you use.. Is there any chance you can share the "repository" field for your package? This line seems to be the culprit: https://github.com/conventional-changelog/conventional-changelog-core/blob/master/lib/merge-config.js#L171 It checks for the host with [a regex](https://github.com/conventional-changelog/conventional-changelog-core/blob/master/lib/merge-config.js#L20). If your url doesn't contain github, it would result in the unknown host and as such cause your problems.

**Comment by patrickmichalina** [comment]
obscuring a little of the actual name, for privacy reasons.

```javascript
"repository": {
    "type": "git",
    "url": "git@sub.corp.company.net:group/some-project.git"
},
```

**Comment by Tapppi** [comment]
Yeah, so the problem is that your host doesn't have "github" in it, resulting in it being detected as an unknown host, causing it to use unknown host defaults for the changelog writes. @stevemao @bcoe I'm not sure how we should proceed with this, I don't think there is any way to autodetect github enterprise.. Maybe there should be an override for the host type?

**Comment by bcoe** [comment]
@Tapppi @stevemao  how about a `standard-version` config stanza in your package.json, allow people to specify an override for repository type. @stevemao could you make it so we can kick this configuration setting along as a hint to the renderer, with it guessing if it's blank?

**Comment by stevemao** [comment]
How about using https://www.npmjs.com/package/cosmiconfig to get the config?

**Comment by Tapppi** [comment]
:+1: for using cosmiconfig, seems super simple! What should we use as options? e.g.
```
// I like:
package.json `{"standard-version": {...}}`
.standard-version (or .standard-version.yaml/.standard-version.json??)
// I dont like, but am open to:
standard-version.config.js
`--config` CLI arg, since we have IMO very good cli options
```

**Comment by bcoe** [comment]
@Tapppi @stevemao definitely a bit biased, _but_ I maintain yargs., and its config management is pretty slick at this point:

https://github.com/yargs/yargs#configkey-description-parsefn

It supports both config files, package stanza configuration, and allows you to extend other config files.

**Comment by patrickmichalina** [comment]
```bash
# I tend to favor:
package.json `{"standard-version": {...}}`
```

**Comment by bcoe** [comment]
@Tapppi @stevemao, actually., since we already use yargs in `standard-version` I think we basically just need to have `.pkgConf('standard-version')` as soon as we're ready to have some configuration options:

https://www.npmjs.com/package/yargs#pkgconfkey-cwd

**Comment by stevemao** [comment]
Sorry didn't know yargs already did it :) Sounds good :)

**Comment by Tapppi** [comment]
Sounds great, had no idea it could do that, yargs is just so big that I can never remember all the stuff it does!

**Comment by stevemao** [comment]
Maybe we could also use [commitizen's `.czrc` file](https://github.com/commitizen/cz-cli#using-the-command-line-tool)? since folks using this module maybe already using commitizen

**Comment by bashmish** [comment]
I would suggest to have a different config file for standard-version, because it seems to be pretty independent from other tools and should stay such. And https://github.com/davidtheclark/cosmiconfig would be awesome. I can work on a MR.

@bcoe can you confirm that you are interested in supporting this feature?

**Comment by knksmith57** [comment]
while I do favor migrating to `cosmiconfig`, the feature I find myself wishing `standard-version` provided is the ability to carve lifecycle scripts _out_ of `package.json` and into a separate file.

it looks like, with a small amount of tweaking, [this is possible w/ the existing `yargs` setup](https://github.com/yargs/yargs/blob/HEAD/docs/advanced.md#configuration).

are there any objections to enabling configuration via external file _if_ `yargs.config()` is used to do so, @bcoe?

**Comment by bcoe** [comment]
@patrickmichalina 👋 took a while, but we finally added the ability to customize URLs, as of `standard-version@6.x.x` you can now specify `compareUrlFormat`, `commitUrlFormat`, etc., which allow to specify URL patterns other than GitHub.com.
