### ISSUE TITLE
Option to remove "v" from the git tag

### ISSUE THREAD

**Issue by Mauricio28** [conventional-changelog/standard-version#153]
Just curious, is there any option to remove the "v" from the git tag?  I know some people use the "v" in front of the version number convention, but others don't.

**Comment by Tapppi** [comment]
Actually this just landed in standard-version `v4.0` via #143! `standard-version --help` outputs usage for the option:
```
...
--tag-prefix, -t     Set a custom prefix for the git tag to be created  [string] [default: "v"]
...
```
@bcoe should this be explicitly documented in the readme if this is such a concern?

**Comment by Mauricio28** [comment]
Boom! You guys are awesome, thanks.

**Comment by rkristelijn** [comment]
For the sake of other users: when you have added `"release" : "standard-version"` to `package.json` use this to tag without the `v`-prefix

`npm run release -- --tag-prefix=''`
