### ISSUE TITLE
Is it possible to update an arbitrary file with the generated version number?

### ISSUE THREAD

**Issue by edsilv** [conventional-changelog/standard-version#155]
When running `standard-version` is there a hook between the "update files" and "git commit" stages that I can use to update a file with the new version number? This is to allow the app's current version to be visible in the UI.

**Comment by bcoe** [comment]
@edsilv they way I've approached this in the past, is to have an application explicitly load the package.json:

https://github.com/yargs/yargs/blob/master/yargs.js#L692

You know that the `package.json` will be available with your module, and that it contains an up-to-date version. Would this work for your use-case?

**Comment by edsilv** [comment]
@bcoe We're going to give that a try, many thanks.
