### ISSUE TITLE
what should our behavior be with lerna

### ISSUE THREAD

**Issue by bcoe** [conventional-changelog/standard-version#156]
I've been investigating moving a few of my repos over to [lerna](https://github.com/lerna/lerna). [Automated CHANGELOG generation](https://github.com/yargs/yargs/blob/master/CHANGELOG.md) has become an important part of my workflow -- helping me quickly bisect bad releases.

I'd like to raise the question _what should our behavior be with lerna?_

* should we be creating CHANGELOG for each package in the lerna repo?
* should we generate a top level CHANGELOG for the lerna repo instead? (this seems like it might fit better with our flow).

I've created a testing repo which I'm going to start noodling in:

https://github.com/bcoe/standard-version-lerna-test

@hzoo, @Tapppi do you have any thoughts on this subject -- once we figure out a happy path for automatic CHANGELOG mangement in lerna, maybe this is even something we could add to the lerna project?

**Comment by hzoo** [comment]
real quick: we setup https://github.com/lerna/lerna-changelog which is a simple script that uses github tags to label prs but from the original pr there was talk of using coventional changelog, and a fork of semantic release etc for lerna https://github.com/lerna/lerna/pull/29#issuecomment-200578545

**Comment by bcoe** [comment]
@hzoo I like this 👍 I had a chance to experiment a bit more; I think I'm going to extend on our tag parser slightly, so that it supports tags in the format: `foo-module@1.3.0`, which will allow me to create a changelog on a package by package basis.

**Comment by bcoe** [comment]
see: https://github.com/lerna/lerna/pull/665
