### ISSUE TITLE
bug: chore commits increment patch version, but they shouldn't

### ISSUE THREAD

**Issue by joefraley** [conventional-changelog/standard-version#163]
Unless I'm missing something this is a pretty severe bug.  Version patches up for chore commits, maybe others.

[Click here for minimal example repo here](https://github.com/joefraley/semver-demo)

![git log](https://www.evernote.com/l/Ae9EvLAgoblNFbkrL2uXOx-U506ir7eKHZQB/image.png)

## Environment
    "commitizen": "2.9.6",
    "cz-conventional-changelog": "2.0.0",
    "standard-version": "4.0.0"

Node 7

## Repro
1. Add changes
2. npm run commit
3. set type as a chore, no breaking changes
4. npm run release
5. see the version increment when it shouldn't

## Example actions
```bash
# commit some changes using commitizen
$ npm run commit
Line 1 will be cropped at 100 characters. All other lines will be wrapped after 100 characters.

? Select the type of change that you're committing: chore   # <---- a chore
? Denote the scope of this change ($location, $browser, $compile, etc.):
 dev
? Write a short, imperative tense description of the change:
 add npm run commit command
? Provide a longer description of the change:
 so people can test if they dont have git cz global
? List any breaking changes:

? List any issues closed by this change:

[master 79ab9f4] chore(dev): add npm run commit command
 1 file changed, 2 insertions(+), 1 deletion(-)

$ gst
On branch master
nothing to commit, working tree clean

# run standard
$ npm run release

> cz-meridian@0.0.0 release /Users/fraleyj/experiments/standard-v-demo
> standard-version

✔ bumping version in package.json from 0.0.0 to 0.0.1 # <--- bad
✔ outputting changes to CHANGELOG.md
✔ committing package.json and CHANGELOG.md
✔ tagging release 0.0.1
ℹ Run `git push --follow-tags origin master; npm publish` to publish
```

**Comment by Tapppi** [comment]
Uhh, the you cannot release two versions with the same version number, so the increment is done to patch. I mean, sometimes you have to make chore changes and still release a fix, in these cases we usually write a custom message in the changelog afterwards.. What did you expect as a result?

**Comment by joefraley** [comment]
I expect the version tool to be a no-op if none of the current commits are a fix/feat/breaking change. Like commit 1000 chores/docs/perfs, run standard, see nothing change.

**Comment by bcoe** [comment]
@Tapppi @joefraley I _think_ this design decision is correct; a great example is making an edit to your README.md; I'll frequently do this, and want an updated page on npmjs.com -- so I'll want to increment a patch even though my commit was something like:

`docs: fix my horrible spelling`

@joefraley if you commit 1000 chores to master, and then run standard-version once, you'll only increment by one patch release.

**Comment by joefraley** [comment]
@bcoe I see. Your commit message suggests this to me:

> (fix): spelling mistake in docs.

In which case everything would be fine.

I'm using standard to go to GitHub and NOT npm (otherwise I would use semantic-release) to control and track web site releases, but I appreciate that semver is designed specifically with tools in mind.

**Comment by joefraley** [comment]
Does that seem wrong to you? If you're chore commit literally has the word "fix" in the body, it shouldn't be a fix commit? 

I guess I'll just fork and make this configurable, but I had hoped for better reception to this idea. For example, this is how semantic-release treats `(chore)`'s, which is  popular workflow.

**Comment by Tapppi** [comment]
With semantic release, you are forced to have a very strict commit guideline. With standard version you choose when you release. If you're change doesn't affect any code etc., it is advised as a chore/docs etc. But you might still want to release it. Standard-version allows that, but it isn't possible with semantic release. It is simply the tradeoffs of similar but different workflows. I think however this is a strength, not a weakness of `standard-version`.

**Comment by navrkald** [comment]
Still believe this is bug, as far as I understand [Conventional Commits specifications](https://www.conventionalcommits.org/en/v1.0.0/):

> Additional types are not mandated by the Conventional Commits specification, and have no implicit effect in Semantic Versioning (unless they include a BREAKING CHANGE). A scope may be provided to a commit’s type, to provide additional contextual information and is contained within parenthesis, e.g., feat(parser): add ability to parse arrays.

Additional types shouldn't contribute to versioning.

However if there is not agreement on this, it would be good if this behaviour could be at least configurable so if someone want to skip creation of new version, if there wasn't any new feature, bugfix or breaking change.
