### ISSUE TITLE
Allow passing a an optional conventional-changelog "preset" option

### ISSUE THREAD

**Issue by lancecaraccioli** [conventional-changelog/standard-version#169]
Not all consumers of standard-version are on github, but would like to take advantage of the workflow provided by the standard-version project.  Allowing consumers to pass a conventional-changelog preset option will give them the ability to create custom configurations that suit their needs e.g. conventional-changelog-upwork

**Comment by Djiit** [comment]
The option `--preset`exists now, maybe we should close this one ?

**Comment by perfectlyimaginary** [comment]
#508

**Comment by jbottigliero** [comment]
As previously mentioned the `--preset` option grants this functionality and supports additional presets found in the conventional-changelog ecosystem as well as custom presets. Thanks all!
