### ISSUE TITLE
Using standard-version with git-flow

### ISSUE THREAD

**Issue by ddellamico** [conventional-changelog/standard-version#173]
Hello !

I'm using git-flow AVH and instead of master branch I'm using "develop".
My question is : It's possibile to configure standard-version to use "develop" branch ?

Thanks you !

Damien

**Comment by bcoe** [comment]
@ddellamico sorry for the slow response 👋 been absolutely buried these days.

I believe you should be able to use standard-version as is, with a branch other than `master` for the final step of pushing tags, just push at develop rather than at master (unless I'm missing something!)

**Comment by stevemao** [comment]
The tool should be agnostic to what your main branch is as long as you release from the right one.
The actual flow will be different than README, but the idea is the same.
I'll be using git-flow with the tool soon so I'll keep an eye on the problems. BTW, according to https://danielkummer.github.io/git-flow-cheatsheet/, you should still generate your CHANGELOG from `master`.

**Comment by ddellamico** [comment]
Thank you guys for your answers!

**Comment by Nysosis** [comment]
Apologies for the necro-threading here! I'd rather not raise a 3rd issue on this.

@stevemao Did you ever get to a point of gitflow working nicely? I'm still a little confused how it can work with pure git-flow, as my releases should happen off of develop, but as the tags are on master, when I come to do a `standard-version` on my release branch, it doesn't know about any of the tags on master, as master should never end up back into develops history (from my understanding)

You claimed
> BTW, according to https://danielkummer.github.io/git-flow-cheatsheet/, you should still generate your CHANGELOG from `master`.

But I can't see anywhere in the current version of that page that recommends it.
