### ISSUE TITLE
semver.prerelease is not a function

### ISSUE THREAD

**Issue by brandondurham** [conventional-changelog/standard-version#175]
When running `yarn release` I’m getting the following error:
```
➜  git:(master) ✗ yarn release
yarn release v0.23.4
$ standard-version --prerelease alpha
/Users/me/Sites/front-end/node_modules/standard-version/index.js:115
  return Array.isArray(semver.prerelease(version))
                              ^

TypeError: semver.prerelease is not a function
    at isInPrerelease (/Users/me/Sites/front-end/node_modules/standard-version/index.js:115:31)
    at getReleaseType (/Users/me/Sites/front-end/node_modules/standard-version/index.js:83:9)
    at /Users/me/Sites/front-end/node_modules/standard-version/index.js:29:25
    at /Users/me/Sites/front-end/node_modules/standard-version/index.js:155:7
    at /Users/me/Sites/front-end/node_modules/conventional-recommended-bump/index.js:83:9
    at ConcatStream.<anonymous> (/Users/me/Sites/front-end/node_modules/concat-stream/index.js:36:43)
    at emitNone (events.js:91:20)
    at ConcatStream.emit (events.js:185:7)
    at finishMaybe (/Users/me/Sites/front-end/node_modules/readable-stream/lib/_stream_writable.js:475:14)
    at endWritable (/Users/me/Sites/front-end/node_modules/readable-stream/lib/_stream_writable.js:485:3)
error Command failed with exit code 1.
```
This is the script in my `package.json` file:
```
"release": "standard-version --prerelease alpha",
```
… and the current version number:
```
"version": "2.0.0-alpha.9",
```

Any idea what might be going on?

**Comment by brandondurham** [comment]
Reinstalling `standard-version` resolved the issue.

**Comment by brandondurham** [comment]
I’m have to reinstall once a week, when I do my releases. It fails every time, any time I try to run it after doing a release.

Suggestions?

**Comment by bcoe** [comment]
@brandondurham I believe this is most likely an issue with yarn; my guess is that when applying it's hoisting logic it's overwriting the version of `semver` used by `standard-version` with an older version of `semver` used deeper in your dependency tree.

Mind opening an issue on `yarn` and referencing this issue? I bet they'll appreciate it.

**Comment by bcoe** [comment]
@brandondurham closing this issue, as I believe it's 99% likely to be related to a bug with `yarn` de-duping -- happy to chime in on the issue you open on yarn, and am happy to help in any way I can to help resolve the issue.
