### ISSUE TITLE
Recommend using --tag argument for prerelease in readme instructions

### ISSUE THREAD

**Issue by tmcw** [conventional-changelog/standard-version#183]
Nothing [this post from Mike Bostock](https://medium.com/@mbostock/prereleases-and-npm-e778fc5e2420), as well as the current behavior of npm, would it be preferable for standard-version to say

```
ℹ Run `git push --follow-tags origin master; npm publish --tag alpha` to publish
```

Instead of always

```
ℹ Run `git push --follow-tags origin master; npm publish` to publish
```

Which causes prerelease releases like 3.1.0-alpha.0 to be installed instead of stable releases?

**Comment by stevemao** [comment]
We have `--prerelease` option. Maybe `--tag` should be the same value of it?

**Comment by bcoe** [comment]
@stevemao @tmcw I agree, if you use `--prerelease`, let's also suggest publishing with a `--tag`.

**Comment by tmcw** [comment]
👍 cool, I think I can knock that out later tonight!
