### ISSUE TITLE
Recommend correct branch for repositories with non-master defaults?

### ISSUE THREAD

**Issue by tmcw** [conventional-changelog/standard-version#184]
Working in a repository in which `gh-pages` is the main / only branch, the recommended publishing step:

```
git push --follow-tags origin master; npm publish
```

Will always fail, because `master` is not a valid branch. Could standard-version check for the main branch and recommend it?

**Comment by stevemao** [comment]
> Could standard-version check for the main branch and recommend it?

Probably just check the current branch and use it's name.

**Comment by tobiasbueschel** [comment]
Thanks for raising this issue ticket @tmcw 👌I also have a similar use case.

On the same note, it would also be nice if there was a way of suppressing `standard-version` from printing `npm publish` or customising the success message altogether.

Some projects might not need to run `npm publish` locally as the command might already be part of the CI/CD pipeline.

**Comment by tmcw** [comment]
Fixed in #331!
