### ISSUE TITLE
Recurring commit in new versions

### ISSUE THREAD

**Issue by pkkummermo** [conventional-changelog/standard-version#194]
There seems to be a bug where two old commits is recurring in all my new releases.

The first time this happened was when I released a patch with no actual commits to be included in the CHANGELOG, ie it was only refactors. Since then the two commits have been following the new releases.

Any tips to what might be wrong?

Spec:
node: 8.1.2
npm: 5.0.3
version:  ^4.2.0

**Comment by stevemao** [comment]
If two commits only include refactors, it should never be printed to the CHANGELOG.

**Comment by pkkummermo** [comment]
Ah sorry, no. I'll try to explain:

This is the CHANGELOG where it first occured:
```
0.17.0 (2017-06-15)

Bug Fixes

createGatewayDialog: correctly handle 409 (3ed2398)
Features

hard-source-webpack: add caching layer for development (e848444)
```
This was a release which consisted solely of refactors, and nothing should be displayed in the changelog. After this release the commit 3ed and e84 has come up on every release making me have to remove them manually from the CHANGELOG.

Ex:
```
0.18.0 (2017-06-16)

Bug Fixes
...
createGatewayDialog: correctly handle 409 (3ed2398)
...
Features

...
hard-source-webpack: add caching layer for development (e848444)
...
```

**Comment by stevemao** [comment]
Have you tagged each release?

**Comment by pkkummermo** [comment]
Yup! Interesting enough, when writing `git log --oneline` I get this
![tag in --oneline](https://user-images.githubusercontent.com/1799456/27254037-3e17997c-5380-11e7-9aae-4de9c0a483f5.png) for old tags and this 
![tag in --oneline 2](https://user-images.githubusercontent.com/1799456/27254039-499f21d4-5380-11e7-9d73-c5ff833b040a.png) for newer tags.

When writing `git tag` I get this.
![tags](https://user-images.githubusercontent.com/1799456/27254044-580c20fa-5380-11e7-8de6-81eab2eb5042.png)

My git version is 2.13.0.

**Comment by stevemao** [comment]
Your tag `v0.16.2` is not tagged on your commit `25781ca`. You might have branched off it and never merged the same commits back

**Comment by pkkummermo** [comment]
Aaah, could this be a result of me amending in the package-lock file after running `standard-version`? Might just fix itself if standar-version includes this by default now :) I'll give it a go during the day and close the issue if so.

**Comment by pkkummermo** [comment]
The amend did indeed change the hash meaning the tag was left "hanging", meaning standard-version latched on the latest tag which had a hash in the history. When adding `package-lock` as a separate commit _after_ the standard-version one everything works.
