### ISSUE TITLE
Undocumented defaults

### ISSUE THREAD

**Issue by czajkowski** [conventional-changelog/standard-version#198]
I was looking for a way to change a default release commit message from an CLI command. 
I couldn't find this option in the docs but it is possible by adding --message and overriding values specified in defaults.json.
Is this a recommended feature to use or are you planning to change/remove it in future versions?

**Comment by stevemao** [comment]
If you run `standard-version --help` you should see all available options. You should see `--message`

**Comment by czajkowski** [comment]
Thank you.
