### ISSUE TITLE
Changelog links are incorrect for selfhosted gitlab

### ISSUE THREAD

**Issue by AdamWillden** [conventional-changelog/standard-version#204]
I know the code attempts to best guess at the host type (gitlab, github, etc) based on the `repository` settings in the `package.json`, the changlog is then formatted with links as appropriate to the host type. Our gitlab server host name is very 'corporate' and unfriendly and does not contain the name 'gitlab'.

I suspect that [get-pkg-repo...index.js#L82](https://github.com/stevemao/get-pkg-repo/blob/ad3a6131b84fa5e85b1b5cbe4cfd0c4409c727a7/index.js#L82) is returning an `unknownHostedInfo` object. I don't know for sure.

I've looked through the code but cannot determine how best to fix this... I was hoping for something simple.

What would be great is if the user could specify what host type to use, and when not provided use the current auto-detection mechanism.

**Comment by stevemao** [comment]
Is this the same as https://github.com/stevemao/get-pkg-repo/issues/9?

**Comment by a-jackson** [comment]
Yes, I think it might be

**Comment by AdamWillden** [comment]
@Stevemao i asked @a-jackson to look into it whilst I'm ok holiday. So what he says goes :-)

**Comment by cdupetit** [comment]
@AdamWillden : Does this PR (#174) answer your question ?

**Comment by AdamWillden** [comment]
@cdupetit yes that is it! #174 addresses this issue directly. 

Given we're both using gitlab I'd have been fine with a `--type gitlab` style fix but I'm absolutely fine with the `--context <context.json>` fix you have proposed there which gives much finer control and may prove useful.

I'd love to have this working!!

FWIW: I Inspected the changes in stevemao/get-pkg-repo#9 in the end myself and didn't see how it would fix our problem after all (I forgot to report that here however).

**Comment by AdamWillden** [comment]
I'd be fine for you to reference this issue in that commit (such that merging will close this issue)

**Comment by bcoe** [comment]
@AdamWillden please see comments in #227

**Comment by bcoe** [comment]
@AdamWillden we finally have this functionality, as of `standard-version@6.x.x`, you can now create a `.versionrc` with custom URL formats [see](https://github.com/conventional-changelog/conventional-changelog-config-spec) for all the config settings that are available.

**Comment by AdamWillden** [comment]
Thank you, very good of you to follow up and let me know.
