### ISSUE TITLE
How to use --skip on CLI

### ISSUE THREAD

**Issue by weaintplastic** [conventional-changelog/standard-version#209]
Hey 👋🏻,
this is a "am I too stupid to use it or is it actually a bug" kind of thing.

I try to use the cli with the skip parameter which is expecting an object. But how do I exactly pass an object via CLI?

**Comment by stevemao** [comment]
I don't think you pass it via cli. you write it in your package.json

**Comment by weaintplastic** [comment]
But it is documented in the cli --help output. So if I can't use it, it shouldn't be there. But I'd appreciate support for it.

**Comment by e-cloud** [comment]
@weaintplastic you should see here https://github.com/yargs/yargs/blob/master/docs/tricks.md#objects

standard-version use yargs as cmd parser, so that's the way to use object input

A example should be:

```
standard-version --skip.xxx=true --skip.xxx=true
```

**Comment by weaintplastic** [comment]
Uh nice! thanks a thousand times @e-cloud

**Comment by stevemao** [comment]
@e-cloud Thanks! Should probably be better documented 😄
