### ISSUE TITLE
Let `standard-version` do the redundant steps.

### ISSUE THREAD

**Issue by sarbbottam** [conventional-changelog/standard-version#21]
IMHO, `standard-version` should perform the below action.

* `checkout master.`
* `git push --follow-tags origin master; npm publish`

**Comment by nexdrew** [comment]
@sarbbottam Thanks for the suggestion!

IMO that would be somewhat contrary to the goals of `standard-version`. In cases where you may need to release a hotfix from a branch other than `master`, your recommended steps would not exactly apply.

As discussed in #22, folks that are comfortable with auto-pushing/publishing should prefer `semantic-release` over `standard-version`.

**Comment by sarbbottam** [comment]
Thanks!
