### ISSUE TITLE
Anchor tag in bit bucket

### ISSUE THREAD

**Issue by love1024** [conventional-changelog/standard-version#212]
Anchor tag does not resolve in bit bucket
e.g <a name="0.0.1" ></a>
This shows as such in bit bucket markdown file.

**Comment by bcoe** [comment]
@love1024 see https://github.com/conventional-changelog/standard-version/issues/154#issuecomment-347768419, I would like to introduce some configuration options for this.

**Comment by bcoe** [comment]
@love1024 we finally have this functionality as of `standard-verison@6.x.x` you can create a `.versionrc` and tweak any of the config options described here:

https://github.com/conventional-changelog/conventional-changelog-config-spec
