### ISSUE TITLE
html in commit message wrecks markdown

### ISSUE THREAD

**Issue by brewingcode** [conventional-changelog/standard-version#222]
```
git commit -am 'fix: put <script> at end of body'
standard-version
git push --follow-tags
open $url_to_changelog
```

...and I see:

![image](https://user-images.githubusercontent.com/1566363/33091461-1185fa1e-ceac-11e7-9698-9deec81ff746.png)

All that has to be done is to escape `<` with `\<`, but I could not for the life of me track down in the morass of packages where to do this.

edit: would be happy to submit a PR if I could get a lead on where to look :-)

**Comment by brewingcode** [comment]
Current workaround is to use a postchangelog lifecycle hook to do this escaping by hand:

```
#!/bin/sh

perl -pi -e '
unless (/^<a name=".*?"><\/a>/) {
  s/(?<!\\)</\\</g;
}
' CHANGELOG.md

**Comment by stevemao** [comment]
The message is rendered as markdown. So you should probably write 

```markdown
fix: put `<script>` at end of body
```

**Comment by brewingcode** [comment]
I....guess that makes a certain amount of sense. I was hoping it would be possible to both keep the markdown AND prevent a stray `<` from borking the view of the changelog.
