### ISSUE TITLE
Commit body does not end up in CHANGELOG.md

### ISSUE THREAD

**Issue by Antontelesh** [conventional-changelog/standard-version#235]
When I release a new version based on commits that contain header and body, the body is not being put into `CHANGELOG.md`.

Example of a commit message:

```
feat(scope): add some stuff

Here's the description of a feature that I want to be inserted into CHANGELOG.md on release.
This description is sometimes long, but is still compatible with the convention.

The body could have more that one paragraph.

fixes: #123
```

**Comment by stevemao** [comment]
@Antontelesh do you have a sample repo?

**Comment by Antontelesh** [comment]
Hi @stevemao, I have created one: https://github.com/Antontelesh/calculator

Please, check the commits there: [link](https://github.com/Antontelesh/calculator/commits/master)
And then the generated `CHANGELOG.md`: [link](https://github.com/Antontelesh/calculator/blob/master/CHANGELOG.md)

Changelog contains only the titles of commits, but not their bodies.

**Comment by stevemao** [comment]
Well changelogs are supposed to be brief. for the details you can always click on the link. BREAKING CHANGES are by default always in the changelog. If you really wanna include body you could tweak the template in the writer.
