### ISSUE TITLE
[Question] Angular multi-library release

### ISSUE THREAD

**Issue by dtodt** [conventional-changelog/standard-version#265]
Greetings.

I have an issue with an angular project of libraries:

- Project (docs) - 0.0.1
  - Library 1 - 0.0.1
  - Library 2 - 0.0.1

The artifact result of this project is **library1** and **library2**.
They will be always the same version as the docs project.

I've tryed to run the **first-release** command on each library folder, but, when I do the first, it creates a tag, then the second fails.

Maybe it's because a lack of knowledge, but it is possible to generate versions in an angular project like that?

Thanks.

**Comment by alexisbmills** [comment]
@dtodt the first-release script would be applied at the project level. This question is quite old though, perhaps you've worked it out. :)

**Comment by dtodt** [comment]
Hi @alexisbmills, not so old haha.

I've switched to another project then I couldn't working on this.

And I've maybe discover a solution, in it's lib [defaults.json](https://github.com/conventional-changelog/standard-version/blob/master/defaults.json).

I've searched around in Github for 'standard-version skip', and it solved my problem.
All I was needed to do is skip the tag creation, as you can see in my [test project](https://github.com/dtodt/commitest), it works great!

As my question was answered I'm closing this issue.
