### ISSUE TITLE
customized path to package.json

### ISSUE THREAD

**Issue by siddarthmishra** [conventional-changelog/standard-version#271]
Is there a possibility of adding customized path to package.json?
Let's say I have the following folder structure
![untitled](https://user-images.githubusercontent.com/13078248/45939160-1463b300-bfee-11e8-9fb7-bd2c75baae27.png)

First package.json (/project A) has name, scripts, dependencies and **NOT** version.

Second package.json (/project A/src/lib) has name, version, publishConfig and peerDependencies.

On executing standard-version in project root folder, the version needs to be updated accordingly to **src/lib/package.json**.
Currently it is taking root folder package.json which doesn't have version and updating the package.json by adding **version** key with **null** value.

Can it be customized to take path for package.json? If path not provided, behave as existing

**Comment by regseb** [comment]
I have a similar need for a WebExtensions that has the following tree structure:

> - project/
>   - package.json
>   - package-lock.json
>   - src/
>     - manifest.json
>   - test/

The _manifest.json_ file is in the subdirectory _src/_. It would be nice to be able to customize [`Bump.pkgFiles`](https://github.com/conventional-changelog/standard-version/blob/master/lib/lifecycles/bump.js#L54).

**Comment by regseb** [comment]
I open a pull request (https://github.com/conventional-changelog/standard-version/pull/425) to configure metadata files.

**Comment by koyre** [comment]
So are there any ways to specify the path to package that will be updated?

**Comment by phil-lgr** [comment]
I want `standard-version` to update only the package.json and not manifest.json where are we at for this issue? I've had a look at the PR #372

**Comment by regseb** [comment]
@siddarthmishra – Since version [7.1.0](https://github.com/conventional-changelog/standard-version/blob/master/CHANGELOG.md#710-2019-12-08), you can customize path to _package.json_. This configuration should solve your problem:

```json
{
    "packageFiles": "src/lib/package.json",
    "bumpFiles": ["src/lib/package.json"]
}
```

@phil-lgr – As for siddarthmishra:

```json
{
    "packageFiles": "package.json",
    "bumpFiles": ["package.json"]
}
```

@bcoe, @jbottigliero – I think this issue can be closed.

**Comment by jbottigliero** [comment]
Hey All,

Sorry for the confusion folks... I'll see what I can do to help get the latest updates published on the registry. I've opened #531, for now, to try and draw attention to the issue.

As a workaround, it looks like `7.1.0` was tagged as `next`
