### ISSUE TITLE
How to autoupdate `docs` and `chores` in changelog

### ISSUE THREAD

**Issue by BeAce** [conventional-changelog/standard-version#280]
Sorry, I can not find the doc about changlog.
By default, `fix` and `feat` are the only keywords I want `docs` and `chores` to be added to changelog as well.How to do that?

**Comment by chapati23** [comment]
same issue here. would be great if you could pass a config object to `standard-version` or have it honor an existing `commitlint.config.js`

**Comment by majorcool** [comment]
Similar issue. It'll be better if every [ common commit type](https://www.conventionalcommits.org/en/v1.0.0-beta.3/) can be listed in the changelog file.

**Comment by scottkidder** [comment]
Same here, I'm looking for an option to allow inclusion/exclusion of the common commit types but haven't found anything yet.

**Comment by stevemao** [comment]
please continue the conversation in https://github.com/conventional-changelog/standard-version/pull/195
