### ISSUE TITLE
callback in code usage is not work

### ISSUE THREAD

**Issue by huruji** [conventional-changelog/standard-version#288]
I use standard-version in my project, but I found the callback in code usage is not work

my code:

```js
standardVersion({
    }, function(err) {
        console.log('callback')
        if (err) {
            process.chdir(root);
            process.exit()
        }
})
```

output when standard-version is success
![image](https://user-images.githubusercontent.com/15937065/50336618-872aee80-0549-11e9-808d-d2b641efd5b3.png)

output when standard-version is failed

![image](https://user-images.githubusercontent.com/15937065/50336722-c8230300-0549-11e9-9456-0585ded6a8cc.png)

And I made a breakpoint in my code , but it still not work , I have no idea now. **Give me a hand, please**

![image](https://user-images.githubusercontent.com/15937065/50336907-5f885600-054a-11e9-81db-d278d68d6421.png)

**Comment by nexdrew** [comment]
The function exported by the main module (index.js) no longer accepts a callback as a 2nd argument - instead it returns a Promise.

This is a breaking change that was [introduced between version 4.0.0 and 4.1.0](https://github.com/conventional-changelog/standard-version/compare/v4.0.0...v4.1.0#diff-168726dbe96b3ce427e7fedce31bb0bcL14) - meaning the 4.1.0 release _should_ have been 5.0.0. 😞 

It also appears the [**Code usage** portion of the README](https://github.com/conventional-changelog/standard-version/tree/v4.4.0#code-usage) has not been updated to reflect this change either. 😿 

So, apologies, it looks like we goofed up here.

In the meantime, try changing your code to something like this instead:

```js
standardVersion()
  .then(_ => console.log('success'))
  .catch(err => {
    process.chdir(root)
    process.exit(1)
  })
```

**Comment by huruji** [comment]
Oh, **It works**.  👍 **very thank you!**

Returns a Promise is better than using callback, We then need update the docs,  could i make a PR to update it. standard-version is a great project, thank you again! 🎉

**Comment by huruji** [comment]
ok, I will @stevemao
