### ISSUE TITLE
if private module don't append `--tag prerelease`

### ISSUE THREAD

**Issue by whyvez** [conventional-changelog/standard-version#294]
`standard-version 4.4.0`

I've run into an issue with a prerelease for a private module where the `--tag prerelease` `npm publish` option was appended to the final `git push` help text.

```shell
✔ bumping version in package.json from 1.2.0-beta.4 to 1.2.0-dev.0
✔ bumping version in package-lock.json from 1.2.0-beta.4 to 1.2.0-dev.0
✔ outputting changes to CHANGELOG.md
✔ committing package-lock.json and package.json and CHANGELOG.md
✔ tagging release v1.2.0-dev.0
ℹ Run `git push --follow-tags origin master --tag prerelease` to publish
```

Need to wrap this logic within the if `(pkgPrivate !== true)` condition.

refs: https://github.com/conventional-changelog/standard-version/issues/183#ref-commit-709dae1

**Comment by stevemao** [comment]
Thanks @whyvez , must be a bug.
