### ISSUE TITLE
Feature request: support commit description

### ISSUE THREAD

**Issue by DrSensor** [conventional-changelog/standard-version#297]
In usual `git commit`:
```
$ git commit -m 'chore(release): v0.0.0-development' -m '[skip ci]'
```
it will produce
```console
$ git log --format=%s%b -n 1
chore(release): v0.0.0-development
[skip ci]
```

However, in `standard-version`:
```
$ standard-version -m 'chore(release): %s' -m '[skip ci]'
```
produce
```console
$ git log --format=%s%b -n 1
chore(release): 0.0.0-development,[skip ci]
```
---
#### Environment
`standard-version --version` 4.4.0
`node --version` v10.14.1
`npm --version` 6.6.0

**Comment by stevemao** [comment]
The body of a commit is usually very long. Hence we only list short descriptions. You can always click the hash to visit the commit page and see details.

**Comment by stevemao** [comment]
> 72 characters

The tool will still work if you have more than 72 characters.


> skip the CI (via `[skip ci]` or `[ci skip]`)

It is recommended to rebase onto your dev/master branch, so you have a chance to modify your message. You don't usually want to skip ci on these public branches.

**Comment by DrSensor** [comment]
> The tool will still work if you have more than 72 characters.

Not if I set up a git hook then use `commitlint` 😂

> It is recommended to rebase onto your dev/master branch, so you have a chance to modify your message. You don't usually want to skip ci on these public branches.

Ah, that makes sense though I prefer to not use dev branch if there is no frequent PR and the project maintained at slow paces.

How about if someone wants to add extra information on the commit release. For example:
```json
{
  "release:as": "standard-version --skip.commit --skip.tag --release-as",
  "release:ok": "standard-version --sign --commit-all --skip.bump --skip.changelog -m 'chore(release): %s' -m $(cat unrelease.txt)"
}
```

**Comment by stevemao** [comment]
> How about if someone wants to add extra information on the commit release.

You can always manually modify your CHANGELOG.

**Comment by DrSensor** [comment]
Thank you for responding to this issue. Seems pushing this feature is hard :joy:
I think the only way for me to add body message is by using `git commit ammend` (wonder if I can add post hook after `release:ok` just to add a body commit :thinking:)

Ah yes, maybe `standard-version` should return error when using 2 or more `--message` flag :slightly_smiling_face:

**Comment by stevemao** [comment]
For customisation, you can always use conventional-changelog directly. For adding features to standard-version, it needs to be useful for many users as it's meant to be an opinionated wrapper with minimal configurations required.  I may not fully understand your issue here but I think you can also configure commitlint to fit what you need. I don't see editing your existing commit in this project fits the scope here.
