### ISSUE TITLE
"Change Log" vs "Changelog"?

### ISSUE THREAD

**Issue by ybiquitous** [conventional-changelog/standard-version#299]
Hi, I have a question. A `CHANGELOG.md` file generated by `standard-version` has a "Change Log" as the first-level heading now. See ⬇️ 

https://github.com/conventional-changelog/standard-version/blob/25300ff44d398cb48889111fb2b55353265a77db/CHANGELOG.md

Which are the words "Change Log" and "Changelog" correct?

For example, Wikipedia says ["Changelog"](https://en.wikipedia.org/wiki/Changelog), and I see "Changelog" more than "Change Log" (or "Change log") on the internet.

I'm not an English native, so I'm happy if anyone would help this question!

**Comment by stevemao** [comment]
Good question! I usually see "Changelog" instead of "Change Log". But I'll let native speakers to make a call :)

**Comment by patrickblackjr** [comment]
`Changelog` is correct I'm fairly certain. on the https://github.com/olivierlacan/keep-a-changelog/pull/92

See /olivierlacan/keep-a-changelog/

**Comment by ybiquitous** [comment]
Thanks. I would like to change from "Change Log" to "Changelog", but this change may cause a breaking change.

So, I think the following steps to introduce the change:

1. Add new option to change the 1st level heading text in `CHANGELOG.md` like this: ⬇️ 

```diff
-var header = '# Change Log\n\nAll notable changes to this project will be documented in this file. See [standard-version](https://github.com/conventional-changelog/standard-version) for commit guidelines.\n'
+var firstLevelHeading = options.firstLevelHeading || 'Change Log'
+var header = '# ' + firstLevelHeading + '\n\nAll notable changes to this project will be documented in this file. See [standard-version](https://github.com/conventional-changelog/standard-version) for commit guidelines.\n'
```

https://github.com/conventional-changelog/standard-version/blob/aad6a613cfb4f32733ee6b5d7e60ab051e3ba8db/lib/lifecycles/changelog.js#L23

2. On the next major update, the default heading `Change Log` will be changed to `Changelog`.

What do you think about this idea?

**Comment by stevemao** [comment]
If this causes breaking change, I'd say changing it is not necessary since it's a very minor thing

**Comment by cristovaov** [comment]
IMHO, this is more of an easy spelling mistake to fix than a breaking change. I welcome having it corrected when I cut a new release of a project. I've submitted a pull request for it.

**Comment by cristovaov** [comment]
Spelling has been fixed by @bcoe in #335 - discussion can be closed, i'd say! :)

**Comment by bcoe** [comment]
👋 closing, I'll try to have a release out today, as soon as I update all the dependencies with renovate.

**Comment by ybiquitous** [comment]
Good news! 👏 Thanks a lot! 😄

**Comment by bcoe** [comment]
@ybiquitous should be fixed in `standard-version@6.x.x` try it out.

**Comment by ybiquitous** [comment]
@bcoe Thanks. When I tried v6, it was so good! 😊 👍
