### ISSUE TITLE
Custom format message!!!

### ISSUE THREAD

**Issue by MrChe** [conventional-changelog/standard-version#300]
I have unique format message for current project.
I create custom `comitizen` config and custom `commitlint`
for example all my commit look like `EMB:123: lorem ipsum`
for generate this commit i have command for commitizen `npm run commit`, this command generate commit for jira, for example if in jira have bug number 987, my commit look like `EMB:987: lorem ipsum`
Question:
how integrate my custom message in changelog?

**Comment by stevemao** [comment]
For complete customisations, please use https://github.com/conventional-changelog/conventional-changelog
