### ISSUE TITLE
Support for 0.x semver mode

### ISSUE THREAD

**Issue by coreyfarrell** [conventional-changelog/standard-version#308]
I have some a couple components that are currently on version `0.x.x` (but never `0.0.x`).  I'd like to propose a flag to enable `0.x` mode for version bumps.  Right now I have to manually use `standard-version -r minor` for breaking changes, `standard-version -r patch` for non-breaking features.  Bug fix releases already do the right thing.

To be clear, I want something like `standard-version --version-zero`, to block bumping to `1.0.0`, shift the meaning of semver: `0.breaking.(feat|fix)`.  npm allows a dependency on `^0.1.0` to install `0.1.1` but not `0.2.0`, so `^0.1.0` should allow updating to any non-breaking release from `0.1.0`.

**Comment by bcoe** [comment]
we should address this here: https://github.com/conventional-changelog/standard-version/pull/310

I'm very much a proponent of this functionality, and think we should default to it with a breaking change in standard-verison.

**Comment by coreyfarrell** [comment]
@bcoe can we get a release of standard-version that uses conventional-changelog@3.1.9?  If you're not ready to promote the [conventional-changelog/conventional-changelog}(https://github.com/conventional-changelog/conventional-changelog/) modules to `latest` maybe we could get a `next` release of standard-version to use those versions?
