### ISSUE TITLE
parsing error with complicated git replacement

### ISSUE THREAD

**Issue by bcoe** [conventional-changelog/standard-version#31]
```
fix: upgraded dependencies, switched back to angular format (fixes #27), pinned shelljs to version that works with nyc (#30)
```

became garbled.

**Comment by bcoe** [comment]
see: https://github.com/conventional-changelog/conventional-commits-parser/issues/27

**Comment by stevemao** [comment]
Thanks should be fixed now

**Comment by bcoe** [comment]
@stevemao awesome, greenkeeper will hopefully push the new version at us.

**Comment by stevemao** [comment]
No, I didn't pin the version in conventional-changelog. So if you do `npm update` it will get the latest version.

**Comment by stevemao** [comment]
@bcoe I think this issue can be closed. I just manually tested on my local machine.
