### ISSUE TITLE
First version initialization when using git tags fallback

### ISSUE THREAD

**Issue by denouche** [conventional-changelog/standard-version#312]
Hello,

https://github.com/conventional-changelog/standard-version/blob/387eaae85827481093ef0aa76a9b5581962842fe/lib/latest-semver-tag.js#L8

When fallback to git tags for version and no existing version is found, the default one is `1.0.0`.

It could be great to have a default version to `0.0.0`, so the first generated version would be `0.0.1` or `0.1.0` or `1.0.0` depending on your commits.

What do you think about that?

**Comment by stevemao** [comment]
`1.0.0` is the default when you do `npm init`. And starting with v1 is kinda the recommendation in npm community now since v0 is a bit confusing and it's ok to spam major version.

**Comment by denouche** [comment]
Alright. Thanks for your answer!
