### ISSUE TITLE
Non-json files support for version bump

### ISSUE THREAD

**Issue by sobolevn** [conventional-changelog/standard-version#313]
Hi, thanks for this awesome tool!

I am using this project with great success with `node` eco-system.
But, I also use other languages as well. And these languages have different meta-files format.
For example,
- `elixir` uses `mix.exs`, docs: https://hexdocs.pm/mix/Mix.html
- `python` uses `setup.py`, docs: https://docs.python.org/3/distutils/setupscript.html
- - `python` + `poetry` use `pyproject.toml`, docs: https://github.com/sdispater/poetry
- - `python` + `pipenv` use `Pipfile`, docs: https://github.com/pypa/pipfile

And not to mention `cargo.toml` for `rust`, `haskell`, `nix`, etc.
It is clear that it is impossible to know about all these formats in advance.

So, I suggest to add some kind of `regex` or `sed` provider to change version inside these files. What do you think?

Thanks!

**Comment by jbottigliero** [comment]
Hey – thanks for the suggestion, I agree that this is something that would be useful! 

I'm going to link this ticket to #271 as it seems like the implementation should be able to resolve both issues.

---

At the moment the `bump` lifecycle (`bump.js[updateConfigs]`) is explicitly parsing the file where we write the version as JSON, but it seems like we should be able to alter this behavior based on a configuration value. There are some overhauls in configuration happening at the moment that we should probably land before adding more options, but I'm putting this on my radar. 

Thanks again!

**Comment by Heziode** [comment]
Another approach, maybe add a `version` or `.version` file that only contains the current version.

**Comment by Heziode** [comment]
@jbottigliero,

With #372 merged, this issue should be solved/closed, isn'it ?

**Comment by sobolevn** [comment]
Yeap.

**Comment by jbottigliero** [comment]
Hey – while the work here has been completed, keep in mind this has not landed in a published release just yet!
