### ISSUE TITLE
Is it comaptibile with commitizen?

### ISSUE THREAD

**Issue by marcoturi** [conventional-changelog/standard-version#32]
Hi,
I'm trying to use commitizen with standard version but i'm not getting a correct format of CHANGELOG.md. Is Standard-version compatibile with commitizen commit formats? If not which alternative can i use to ensure best practise for commits ?

Thank you

**Comment by marcoturi** [comment]
Update: only bug fix and feature are implemented. Styles and chore for example are not working.

**Comment by bcoe** [comment]
@marcoturi currently `standard-version` uses the angular convention for changelog generation; 

I'd definitely be interested in discussing with @stevemao and @nexdrew about whether we should support a few more verbs.

There are also a few features of the angular template I'd be interested in potentially moving away from, e.g., https://github.com/conventional-changelog/conventional-commits-parser/issues/27

**Comment by stevemao** [comment]
> Styles and chore for example are not working.

This is not true. If they don't contain a `BREAKING CHANGE` they are omitted since they don't make any difference to the end-user (this was discussed in the angular repo).

**Comment by stevemao** [comment]
> I'd definitely be interested in discussing with @stevemao and @nexdrew about whether we should support a few more verbs.

@bcoe You might be interested in https://github.com/conventional-changelog/conventional-changelog/pull/146
https://github.com/Jimdo/changelogrc-spec

**Comment by stevemao** [comment]
Can we close this issue and move the discussion to related issues?
