### ISSUE TITLE
New version generates http:// links in changelog (instead of https://)

### ISSUE THREAD

**Issue by mikl** [conventional-changelog/standard-version#358]
After upgrading from 4.4.0 to 6.0.1, I noticed that the URLs in the changelog are being generated with the wrong protocol (`http` instead of `https`).

In package.json, we have the following:

```json
{
  "repository": "git+https://gitlab.example.net/org/project.git",
}
```

But the changelog links generated look like:

```
* handle deleted flag being NULL ([beef123](http://gitlab.example.net/org/project/commit/beef123))
```

That link may or may not work depending on server configuration, but if your server doesn't have HSTS configured, clicking on such a link would cause an unencrypted round-trip to the server, leaking semi-sensitive data about git repo names and commit IDs if you're on public WiFi.

**Comment by jbottigliero** [comment]
@mikl - thanks for the report. I think this might be related to how we're handling substitutions in the new `conventionalcommits` preset. I have a PR open that addresses a related issue that might also resolve the behavior you are seeing.

**Comment by jbottigliero** [comment]
@mikl – I've [added a test](https://github.com/conventional-changelog/standard-version/commit/8b2a37da8c7b8afb13f41673f15bac07bb8f1866) to try and reproduce the behavior you are seeing... at the moment, it's passing. Could you verify the test matches the configuration you are seeing issues with?  

For reference, this is the raw `CHANGELOG.md` (`content`) generated by the test:

```markdown

# Changelog

All notable changes to this project will be documented in this file. See [standard-version](https://github.com/conventional-changelog/standard-version) for commit guidelines.

## 1.1.0 (2019-05-15)

### Features

* another commit addresses issue [#1](https://github.com/foobar/baz/issues/1) ([a382518](https://github.com/foobar/baz/commit/a382518))
```

**Comment by mikl** [comment]
I find myself unable to reproduce the problem now. I did not keep a package.lock from when I experienced the problem, so maybe it was due to having a bad version of something installed.

In any case, it works now, so thanks for looking into this, at least, and sorry for the unhelpful bug report.

**Comment by jbottigliero** [comment]
@mikl – no worries, thanks for following up!
