### ISSUE TITLE
Add EOL when overwriting package.json

### ISSUE THREAD

**Issue by nexdrew** [conventional-changelog/standard-version#37]
Otherwise changes to package.json b/w releases can end up flip-flopping the last line since editors like Atom will automatically add it but `standard-version` strips it off - just becomes annoying, unnecessary changes in history and in PRs.

I think we just need to change this line:

```js
fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2), 'utf-8')
```

to something like this:

```js
fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + require('os').EOL, 'utf-8')
```

**Comment by stevemao** [comment]
Didn't know about `require('os').EOL`, I used to just use `\n` :D
