### ISSUE TITLE
.versionrc.json is not being loaded

### ISSUE THREAD

**Issue by flyinbutrs** [conventional-changelog/standard-version#371]
`.versionrc.json` is not being loaded currently, only `.versionrc`. This is my `.versionrc.json` file currently:

```bash
$ cat .versionrc.json
{
  "scripts": {
    "precommit": "yo version-file --force --git"
  }
}
```

When I run, note that there's no precommit hook executed:

```bash
$ npm run release -- --dry-run

> generator-version-file@0.1.0 release /Users/drosenbloom/git/generators/generator-version
> standard-version "--dry-run"

✔ bumping version in package.json from 0.1.0 to 0.1.1
✔ bumping version in package-lock.json from 0.1.0 to 0.1.1
✔ outputting changes to CHANGELOG.md

---
### [0.1.1](https://github.com/flyinbutrs/generator-version-file/compare/v0.1.0...v0.1.1) (2019-05-29)
---

✔ committing package-lock.json and package.json and CHANGELOG.md
✔ tagging release v0.1.1
ℹ Run `git push --follow-tags origin master && npm publish` to publish
```

But if I move `.versionrc.json` to `.versionrc` and retry, it does execute the hook.

```bash
$ mv .versionrc.json .versionrc
$ npm run release -- --dry-run

> generator-version-file@0.1.0 release /Users/drosenbloom/git/generators/generator-version
> standard-version "--dry-run"

✔ bumping version in package.json from 0.1.0 to 0.1.1
✔ bumping version in package-lock.json from 0.1.0 to 0.1.1
✔ outputting changes to CHANGELOG.md

---
### [0.1.1](https://github.com/flyinbutrs/generator-version-file/compare/v0.1.0...v0.1.1) (2019-05-29)
---

✔ Running lifecycle script "precommit"
ℹ - execute command: "yo version-file --force --git"
✔ committing package-lock.json and package.json and CHANGELOG.md
✔ tagging release v0.1.1
ℹ Run `git push --follow-tags origin master && npm publish` to publish
```

Tested on v6.0.1.

```bash
$ npm run release -- --version

> generator-version-file@0.1.0 release /Users/drosenbloom/git/generators/generator-version
> standard-version "--version"

6.0.1
```

**Comment by jbottigliero** [comment]
Hey! Thanks for the report – this actually isn't supported in the current release, but I've opened a PR that should account for this functionality.

**Comment by bcoe** [comment]
@jbottigliero I'm a bit confused, I think this issue relates to `.json` format files, not to `.js`. I have a slight preference for not supporting `.js` format, as it can lead to bad habits (your configuration shouldn't be a program IMO).

I would however love to fix this bug.

**Comment by jbottigliero** [comment]
Whoa, yeah... I’ve confused myself taking a second look at this.

Let me review the tests and see what’s going on here!

**Comment by jbottigliero** [comment]
Ah, I see the problem here... it's actually resolved in #357 which will land in the next version @bcoe.

I've opened #381 if we want to ensure coverage for now...

...I think tests deserve a bit of a clean-up with the new configuration patterns, but we can save that conversation for another day.

**Comment by pdsouza** [comment]
I can confirm that `.versionrc.json` is working correctly in `7.0.0`.

**Comment by stevemao** [comment]
Is this addressed? The PR hasn't been merged yet.

**Comment by flyinbutrs** [comment]
Yes, it's working in 7.0.0. Not sure what changed, but it definitely works.
