### ISSUE TITLE
Unable to pass in `skip` to CLI

### ISSUE THREAD

**Issue by godd9170** [conventional-changelog/standard-version#373]
Attempting any of the following in the cli
```sh
standard-version --skip="{\"changelog\":true}"
standard-version --skip='{"changelog":true}'
standard-version --skip "{\"changelog\":true}"
standard-version --skip '{"changelog":true}'
```

returns the error `skip must be an object`

**Comment by bcoe** [comment]
@godd9170 oh, perhaps ignore my comments on your PR, the issue is that you should be passing `--skip` in the format:

`--skip.changelog --skip.foo`

You can also provide these values in a configuration file.

**Comment by godd9170** [comment]
Ahhh that makes way more sense. Thanks @bcoe
