### ISSUE TITLE
Versions in composer

### ISSUE THREAD

**Issue by wyster** [conventional-changelog/standard-version#394]
Hello! I'm about PR #262.

After any changes in composer.json command `composer validate` fail with error:

> The lock file is not up to date with the latest changes in composer.json, it is recommended that you run `composer update`

If use `composer update --lock` hash in composer.lock updated and section `version` removed from composer.lock

Docs:
https://getcomposer.org/doc/03-cli.md#validate
https://getcomposer.org/doc/03-cli.md#update-u

> --lock: Only updates the lock file hash to suppress warning about the lock file being out of date.

I added this trick in standard-version config:
```
"scripts": {
  "postbump": "composer update --lock"
}
```

In total:
1. Not need update composer.lock
2. Need run `composer update --lock` after changes composer.json, but command not very fast

Maybe it's need add to FAQ?

**Comment by bcoe** [comment]
@TilmannBach :wave: sounds like our composer feature might need some updates. Any thoughts?
