### ISSUE TITLE
Help info contains conflicting default values for --preset option

### ISSUE THREAD

**Issue by matatk** [conventional-changelog/standard-version#406]
The help output for 6.0.1 states:

```
  --preset             Commit message guideline preset (default: angular)
                                                        [string] [default: "conventionalcommits"]
```

I gather [the default was changed in 6.0.0 to conventionalcommits](https://github.com/conventional-changelog/standard-version/blob/master/CHANGELOG.md#breaking-changes), but it looks like the reference to angular was not removed.

Thanks for this tool—it's great, and I am really excited to use it since #208 was fixed, as I want to ensure my changelogs are as accessible (e.g. to screen-reader users) as possible. Previously I had written a wrapper for conventional-changelog that modified the heading structure (and did some other stuff that's now supported via the new configuration options), but am looking forward to moving to using standard-version).

**Update:** was just looking at the README and noticed [the README also mentions that standard-version is based on the Angular format by default](https://github.com/conventional-changelog/standard-version#how-is-standard-version-different-from-semantic-release). If this is a separate issue, I'd be happy to file it.

**Comment by jbottigliero** [comment]
Hey, thanks for the report! A fix for `--help` output will land in the next version (#377), I've just opened a PR removing the mention of the Angular convention from the README.
