### ISSUE TITLE
Links in changelog don't include repository name

### ISSUE THREAD

**Issue by jefftienchow** [conventional-changelog/standard-version#410]
The links to my published commits currently don't include a repository name, causing the links to not work.

For ex: https://github.com///compare/v1.0.0...v1.0.1 instead of
https://github.com/repository/name/compare/v1.0.0...v1.0.1

I have changed the name of my repository before, which I suspect could be the issue. Is there a way to configure the changelog so that future release links won't be broken?

**Comment by jbottigliero** [comment]
Hey @jefftienchow – I have a feeling this could be caused by a bug in the new default preset (`conventionalcommits`)...

Could you provide the version of `standard-version` you are running and which preset configuration you are using (if it's _not_ the default)?

**Comment by jefftienchow** [comment]
I was using 6.0.1. Reverting back to 5.0.2 fixed the problem!

**Comment by jbottigliero** [comment]
Great – thanks for the follow-up. 

For tracking purposes, I'm going to link this to conventional-changelog/conventional-changelog#462 (and what I believe is the fix conventional-changelog/conventional-changelog#463) which should land in the next minor version release of `conventional-changelog` (`>=3.1.10`).

**Comment by towry** [comment]
@bcoe I am using standard-version: 8.0.0, still have this issue.
![Jietu20200612-152645](https://user-images.githubusercontent.com/8279858/84476808-44228500-acc1-11ea-8e58-ba248213387b.jpg)

**Comment by ttous** [comment]
Same here with 9.0.0 😢
