### ISSUE TITLE
Question: Is it really a good idea to store version in package.json and git?

### ISSUE THREAD

**Issue by FixRM** [conventional-changelog/standard-version#411]
It is common to protect master with PR's and have some CI pipeline. If version is assigned on CI side it may not be pushed directly to master due to policy. In other hand, pushing version update to master can trigger new CI build and cause a loop.

What is the reason to have version in both tag and json?

**Comment by jbottigliero** [comment]
Hey @FixRM, the answer to that question is going to vary based on your implementation and CI/CD requirements – for the most common case, I'd assume it's to keep things in-sync for package manager requirements (`npm`).

`standard-version` does provide the ability for you to skip both (or one) of the lifecycle events you are questioning if you want to use alternative methods for determining what to bump and when...

If you have an extremely specific requirement you might find using the underlying `conventional-changelog` packages directly a more suitable solution.

Hope that helps!

**Comment by FixRM** [comment]
Thank you @jbottigliero! I finally found a reason of my confusion :) In MS world where I came from, CI/CD operates with two separate terms: "build" and "release". The term "build" is applicable to Web/Node development as well, but meaning is not quite same as with, let's say, .NET development. The main difference, as I see, is that we used to tag "sources" after succesfull build, while you tag already executable code before release. That was confusing to me.

Any way, I want to benefit of `standard-version` features and now like the idea of doing automated tag-commit with some "build'o'release" artifacts such as release notes. But how can I get calculated version for future processing? Should I use `postbump` hook, to read it from package.json or there is more obvious way?

Second question is how can I add "skip ci" flag to commit massage to avoid CI loop?

**Comment by evanjmg** [comment]
Find your answer @FixRM ? In same boat

**Comment by FixRM** [comment]
Hi @evanjmg. Finally I came to something like this: https://fixrm.wordpress.com/2020/02/05/bulletproof-project-template-part-3-devops-automation. In short: yes, it's ok to store version in files. With YAML pipeline it's easy to give build a name in runtime
