### ISSUE TITLE
feat(other): Join "other" commits in the changelog under an "Others" section

### ISSUE THREAD

**Issue by pirix-gh** [conventional-changelog/standard-version#423]
It would look like something like this, to provide a complete changelog. Or am I missing something?

```md
### 3.2.2 (2019-08-01)

### Features

....

### Bug Fixes

....

### Others

chore: ....
perf: ....

```

**Comment by jbottigliero** [comment]
@pirix-gh – I think your use case would be best solved by [configuring](https://github.com/conventional-changelog/standard-version#configuration) the `types` value.

For more details of the structure of the `types` property, check out the [configuration spec](https://github.com/conventional-changelog/conventional-changelog-config-spec/blob/master/versions/2.0.0/README.md#types).


In the example you provided, you'll likely want to wind up with something along the lines of...

```js
  types: [
    {type: 'feat', section: 'Features'},
    {type: 'fix', section: 'Bug Fixes'},
    {type: 'perf', section: 'Others'},
    {type: 'chore', section: 'Others'}
  ]
```

The `types` you define will then map to whatever `section` you want! This configuration _does not_ account for _scopes_, but that is something we could consider as an improvement/feature update if this doesn't solve your issue!

**Comment by pirix-gh** [comment]
I was not very focused, sorry :man_facepalming:. Thank you!
