### ISSUE TITLE
standard-version 7.0.0 does not increase minor version

### ISSUE THREAD

**Issue by huukimit** [conventional-changelog/standard-version#429]
Hello, I'm trying to use standard-version for automating versioning. I created an [demo repository](https://github.com/kimnh-labs/seminar-semver-and-commit-conventional/commits/master) for testing.

Although My version is `v0.1.2` -> I added [a commit](https://github.com/kimnh-labs/seminar-semver-and-commit-conventional/commit/88a27037ad34845e90484f7c5e58d9dd9d235270) started with `feat: ` type then run `standard-version` to release, standard-version didn't increase minor version that I expected v0.2.0.

Anyone here for help! (^^;)

**Comment by ben-mckernan** [comment]
It is because you don't have a major version, see conventional-changelog/conventional-changelog#452

**Comment by huukimit** [comment]
@ben-mckernan I got it. Thank you so much for the link. I think `standard-version` should do that.
