### ISSUE TITLE
Preserve formatting of package.json

### ISSUE THREAD

**Issue by nexdrew** [conventional-changelog/standard-version#43]
See discussion in #38, which was originally meant to address #37 but ended up in a slippery slope of scope creep.

Basically, we overwrite package.json using `JSON.stringify(pkg, null, 2) + '\n'` but this may be too intrusive for folks using Windows line endings (`\r\n` instead of `\n`) or different indentation (tabs instead of spaces, or more than 2 spaces).

Here are a couple ways we could address this:
1. Detect and preserve newline chars and indentation via [`detect-newline`](https://www.npmjs.com/package/detect-newline) and [`detect-indent`](https://www.npmjs.com/package/detect-indent) (similar to #38)
2. Read package.json as string (instead of `require()`ing it) and just replace the `"version"` value, ignoring/preserving all other content/formatting

I think I'd prefer option 2.

I also think our CHANGELOG writing logic should not be affected by this.

**Comment by stevemao** [comment]
Probably should be similar to how `npm-version` does it.

**Comment by bcoe** [comment]
@nexdrew might be worth looking at how greenkeeper does it.

**Comment by nexdrew** [comment]
Looks like [`npm version`](https://github.com/npm/npm/blob/v3.9.6/lib/version.js#L283-L287) pretty much does the same thing that [`standard-version`](https://github.com/conventional-changelog/standard-version/blob/v2.3.0/index.js#L71) does. Hmm, maybe this is a non-issue then...

**Comment by stevemao** [comment]
Is this still an issue?

**Comment by nexdrew** [comment]
@stevemao I think we can close this. If anyone complains we can revisit.

**Comment by ArmandoAssuncao** [comment]
@nexdrew I'm having problems with this, I use 4 spaces in the package.json, but it's changing to 2 spaces.
Could preserve the file, how you said.

tested in v4.3.0

**Comment by stevemao** [comment]
I think we should reopen this since `npm` preserves the format now.

**Comment by hugomrdias** [comment]
please preserve the code format, we are always fixing conflicts on package.json

**Comment by rdbmax** [comment]
Can I submit a pull request for this ? Which option do you prefer ?
> Read package.json as string (instead of require()ing it) and just replace the "version" value, ignoring/preserving all other content/formatting

I am agree with this

**Comment by alasdairhurst** [comment]
I've been looking for this for a while, so just got around to creating a PR for this: #282

**Comment by bcoe** [comment]
@alasdairhurst @nexdrew is this still something anyone would like to take on?

**Comment by alasdairhurst** [comment]
@bcoe see the linked PR I provided - it's already merged and released in 5.0.0!

**Comment by alasdairhurst** [comment]
@bcoe  this can be closed.
