### ISSUE TITLE
How to configure different destination folder with npm publish script?

### ISSUE THREAD

**Issue by ghiscoding** [conventional-changelog/standard-version#441]
I really like this lib and how it automate my processes but I'm trying to add it to a different open source project and that project requires to do `npm publish dist` (where `dist` is the only folder being published). I couldn't find any issue that talks about the configuration of a different publish path. Is that doable?

The release command I run is the following
`yarn run release -- --release-as minor --infile ./CHANGELOG.md`

and the automate script command it produce is the following
`git push --follow-tags origin master && npm publish`

But I would like to have it like this (where `dist` is the only folder published)
`git push --follow-tags origin master && npm publish dist`

**Comment by bcoe** [comment]
standard-version doesn't automatically run `git push`, you should be able to simply run the alternate publication command I think? (even though the CLI recommends a command that won't work for you).

**Comment by ghiscoding** [comment]
Yes I know that it doesn't run the `git push` command, I was just trying to find out if there is a way to produce the correct command, without having to always remember to add `dist` at the end of my command... which I think I will often forget and that breaks my lib :(

**Comment by bcoe** [comment]
@ghiscoding seems like a reasonable thing to expose as a configuration option, then you could put it in your `.versionrc`? any interest in adding this, and I can review?

**Comment by ghiscoding** [comment]
That would be great, except that I never used a `.versionrc`, what does that do? I'm not sure what to do.

**Comment by bcoe** [comment]
allows you to define configuration options for `standard-version`, see:

https://github.com/conventional-changelog/standard-version#configuration

**Comment by ghiscoding** [comment]
I read a few documentation [conventional-changelog/standard-version](https://nicedoc.io/conventional-changelog/standard-version) and the `versionrc` and the [conventional-changelog/conventional-changelog-config-spec](https://github.com/conventional-changelog/conventional-changelog-config-spec) but the fact is that I don't know what to do to contribute. 

What I think would be a good option/setting would be to run my command like this (where I added `--publish-folder dist`)

`yarn run release -- --release-as minor --publish-folder dist --infile ./CHANGELOG.md`

and that would produce the git command

`git push --follow-tags origin master && npm publish dist`

**Comment by 18clans** [comment]
Any solution for this yet to have your own custom instruction message?

**Comment by ghiscoding** [comment]
Unfortunately no, I still have to do it by hand (and I still forget quite often to include `dist` and I have to release multiple versions for that reason)

**Comment by ghiscoding** [comment]
I've opened this a while ago and since then `standard-version` got deprecated and I moved to [release-it](https://github.com/release-it/release-it) which does support this feature, so with all these infos then I guess it's ok to close this issue. Thanks
