### ISSUE TITLE
releaseCommitMessageFormat isn't replacing `%s` in commit-message?

### ISSUE THREAD

**Issue by escapedcat** [conventional-changelog/standard-version#453]
Using this:
```
{
  "message": "chore(release): %s [ci skip]"
}
```
The commit looks like this:
```
commit 123 (tag: v0.12.2)
Author: me
Date:   Tue Sep 10 10:54:17 2019 +0200

    chore(release): 0.12.2 [ci skip]
```
And I get the info:
```
[standard-version]: --message (-m) will be removed in the next major release. Use --releaseCommitMessageFormat.
```

But when I change this to:
```
{
  "releaseCommitMessageFormat": "chore(release): %s [ci skip]"
}
```

The commit message looks like this:
```
commit 123 (tag: v0.12.3)
Author: me
Date:   Tue Sep 10 10:55:11 2019 +0200

    chore(release): %s [ci skip]
```

Doesn't matter if this is defined in `package.json` or `.versionrc`  
Is this a bug or am I missing something?  
Not sure if this is related to #350

**Comment by tommywo** [comment]
releaseCommitMessageFormat uses different substitutions https://github.com/conventional-changelog/standard-version/blob/a7133cc0e5a1924793bdf0e4abdd0ad9c58dfc2d/index.js#L21

try using `{{currentTag}}` instead of `%s`

**Comment by escapedcat** [comment]
Arg, thanks!

**Comment by dmitrykurmanov** [comment]
I suppose it might be changed in the future, so we could use `standard-version --help` to find out the actual information.

**Comment by codeandcats** [comment]
This should really be documented in the cli help (`standard-version --help`) imo.
