### ISSUE TITLE
"feat:" commits causing PATCH instead of MINOR

### ISSUE THREAD

**Issue by JVMartin** [conventional-changelog/standard-version#454]
We are using version `7.0.0`.

**Expected behavior:**
`feat:` commit messages should result in a MINOR bump.

**Actual behavior:**
`feat:` commit messages result in a PATCH bump.

**Details:**
We have our pipeline set up to release on every commit to master, notice how both `fix` and `feat` result in patches:
![image](https://user-images.githubusercontent.com/4450814/64815754-23bf7180-d55b-11e9-8b46-d0ef0297de74.png)

Here is the output from `standard-version` on a `feat:` release:
```
$ npx standard-version --infile docs/CHANGELOG.md
✔ bumping version in package.json from 0.14.6 to 0.14.7
✔ outputting changes to docs/CHANGELOG.md
✔ committing package.json and docs/CHANGELOG.md
✔ tagging release v0.14.7
ℹ Run `git push --follow-tags origin master && npm publish` to publish
```

Here is the resulting commit:
![image](https://user-images.githubusercontent.com/4450814/64815829-50738900-d55b-11e9-9ac4-940548e75116.png)

**Comment by jbottigliero** [comment]
Hey @JVMartin – as of 7.0.0 this is expected behavior for module versions < 1.0.0.

You can follow the related changeset (and conversation) here: https://github.com/conventional-changelog/standard-version/pull/347

If you don't mind, I'm going to close this as it is expected behavior. If you need to break out of this behavior for a release, consider using the [`--release-as=minor` flag](https://github.com/conventional-changelog/standard-version#release-as-a-target-type-imperatively-like-npm-version).

**Comment by JVMartin** [comment]
Hey @jbottigliero , thanks for the details!

IMO, the behavior of `standard-version` should **not** be different for pre-1.0.0 versions. Let me explain why...

We run `standard-version` automatically in CI, and we really need a way for it to do both minors and patches based on commit messages, even in < 1.0.0. We obviously can't add the `--release-as=minor` flag to the CI, because then _every_ release would be minor.

So it seems like our only options for pre-1.0.0, is to have _every release_ be a PATCH, or _every release_ be a MINOR, which is not great.

If the functionality for pre-1.0.0 were exactly the same as for post-1.0.0, then both automated and non-automated workflows would be supported completely.

Everyone could do a `BREAKING CHANGE:` for major, a `feat:` for minor, and a `fix:` for patch. And the world would live in **perfect harmony**.

Thoughts?

**Comment by JVMartin** [comment]
Also, regarding #347...

The title of the PR is `feat!: bump minor rather than major, if release is < 1.0.0`.

That is, in fact, *exactly* what we need it to do! Currently this is broken, because feat bumps PATCH rather than MINOR, when it is supposed to bump MINOR.

**Comment by JVMartin** [comment]
You know what, I think I misunderstood. :disappointed: 

We can still get a MINOR to happen by doing a `BREAKING CHANGE` in the commit notes of a `feat`.

So actually, we're all set. Thanks much! :smile:

**Comment by coreyfarrell** [comment]
https://github.com/conventional-changelog/conventional-changelog/pull/452#issuecomment-512641237 explains the reasoning for the behavior.  The intent is to work well with npm by allowing caret semver ranges to install all non-breaking updates.
