### ISSUE TITLE
bug: feat is not bumped correctly

### ISSUE THREAD

**Issue by remarkablemark** [conventional-changelog/standard-version#460]
## Issue

Discovered a bug in which `standard-version@7.0.0` does not bump version correctly for type `feat`.

## Expected

`package.json` increments by **minor** version.

## Actual

`package.json` increments by **patch** version.

## Steps to Reproduce

```sh
mkdir test
cd test
git init
npm init -y
git add .
git commit -m "feat: test"
npx standard-version
```

Output:

```
npx: installed 206 in 9.929s
✔ bumping version in package.json from 0.0.0 to 0.0.1
✔ created CHANGELOG.md
✔ outputting changes to CHANGELOG.md
✔ committing package.json and CHANGELOG.md
✔ tagging release v0.0.1
ℹ Run `git push --follow-tags origin master && npm publish` to publish
```

CHANGELOG.md:

```md
# Changelog

All notable changes to this project will be documented in this file. See [standard-version](https://github.com/conventional-changelog/standard-version) for commit guidelines.

### 0.0.1 (2019-10-06)


### Features

* test 022fa96

```

**Comment by tommywo** [comment]
Quoting @coreyfarrell on this as he nicely explained this on slack.
> the current behavior of standard-version is to follow the way npm works.  when you're in 0.x minor bumps are for breaking changes, patch is for non-breaking changes.

> this functionality was introduced in standard-version@7.0.0

> `standard-version -r minor` will do a minor bump regardless of commits
