### ISSUE TITLE
How to customize CHANGELOG generation?

### ISSUE THREAD

**Issue by dpyzo0o** [conventional-changelog/standard-version#464]
Hello everyone

I have read through the documentation, especially this [section](https://github.com/conventional-changelog/standard-version#customizing-changelog-generation).

I would like to change some formats of the auto-generated CHANGELOG and release commit message. e.g `chore(release): 1.0.1` --> `v1.0.1`. Then I find that I just need to change this variable `releaseCommitMessageFormat` explained [here](https://github.com/conventional-changelog/conventional-changelog-config-spec/blob/master/versions/2.1.0/README.md#releasecommitmessageformat-string). But there seems to be no sentences telling me where to set this value. Can someone help me out?

**Comment by tommywo** [comment]
You need to set it in [configuation](https://github.com/conventional-changelog/standard-version#configuration) - there are few possibilities on how to store it.
