### ISSUE TITLE
Version header is h3 instead of h2 when header has a compare link

### ISSUE THREAD

**Issue by negebauer** [conventional-changelog/standard-version#469]
After creating a new repo and running standard version twice the header for the version line is h3 instead of h2, like the following example.

```md
# Changelog

All notable changes to this project will be documented in this file. See [standard-version](https://github.com/conventional-changelog/standard-version) for commit guidelines.

### [1.1.1](///compare/v1.1.0...v1.1.1) (2019-10-25)

## 1.1.0 (2019-10-25)


### Features

* a commit 6dbf7a9
```

You can reproduce this issue by running the following

```sh
mkdir foo
cd foo
npm init -y
npm install -D standard-version
git init
echo -e "node_modules" > .gitignore
git add package.json
git commit -m "feat: a commit"
standard-version
cat CHANGELOG.md
// here the changelog will have a line like
// ## 1.1.0 (2019-10-25)
// with h2, the expected result

standard-version
cat CHANGELOG.md
// here the changelog will have a line like
// ### [1.1.1](///compare/v1.1.0...v1.1.1) (2019-10-25)
// with h3, which isn't the expected result, it should be h2
```

**Comment by tommywo** [comment]
That's a feature, not a bug ;) h3 for patches, h2 for others. https://github.com/conventional-changelog/conventional-changelog/blob/814f878054ca3c9ec00c3147478eb1e6a2762e9a/packages/conventional-changelog-conventionalcommits/templates/header.hbs#L1

**Comment by LuckyDottie** [comment]
Is there a way to keep the rules same as before? this feature made my document's structure massy.

**Comment by tommywo** [comment]
@LuckyDottie you can set custom template in writerOpts. This is not a new feature, it's a least 2 years old. Same thing is in angular preset, but with h2 and h1. take a look https://github.com/angular/angular/blob/master/CHANGELOG.md

**Comment by negebauer** [comment]
oh didn't know it was an issue, thanks!

**Comment by negebauer** [comment]
@tommywo could you direct me to documentation about custom template in writerOpts?

**Comment by negebauer** [comment]
and by the way, why is it h3 for patches? I thought this was based on [keepachangelog](https://keepachangelog.com/en/1.0.0/) which users h2 for all versions

**Comment by Yogu** [comment]
> and by the way, why is it h3 for patches? I thought this was based on [keepachangelog](https://keepachangelog.com/en/1.0.0/) which users h2 for all versions

Agree, this is really weird because

- the types like "Bugfixes" are now on the same level as the versions
- patches appear as subheadings of the *next* minor/major release. If the last release is a patch release, a heading level is missing.

To me, [the result](https://github.com/conventional-changelog/standard-version/blob/v9.3.2/CHANGELOG.md) just looks broken
