### ISSUE TITLE
Invalid Version: undefined

### ISSUE THREAD

**Issue by abelland** [conventional-changelog/standard-version#471]
I am trying to `standard-release` on my projects and it works on most repositories.

For some reason, on some repositories I get **Invalid Version: undefined**

`standard-release` is installed globally

am I missing something?

**Comment by abelland** [comment]
just missing package.json file

**Comment by GiancarlosIO** [comment]
@abelland I'm getting the same error. What was your solution for this? 🤔

**Comment by abelland** [comment]
> @abelland I'm getting the same error. What was your solution for this? 🤔

create an empty package.json file
