### ISSUE TITLE
prebump script not affecting version

### ISSUE THREAD

**Issue by cgx** [conventional-changelog/standard-version#473]
Specifying a *prebump* script in either a package.json or .versionrc.json will be properly executed but the stdout won't affect the version:

```bash
❯ standard-version --dry-run
✔ Running lifecycle script "prebump"
ℹ - execute command: "echo 9.9.9"
✔ bumping version in package.json from 4.0.8 to 4.0.9
✔ outputting changes to CHANGELOG.md
...
```

**Comment by tommywo** [comment]
It doesn't supposed to. If you need to bump to specific version use this: https://github.com/conventional-changelog/standard-version#release-as-a-target-type-imperatively-like-npm-version
