### ISSUE TITLE
Question: configuring different issue URL?

### ISSUE THREAD

**Issue by JamieMason** [conventional-changelog/standard-version#48]
I've tried quite a few approaches and searched around and still can't seem to get this working, I was wondering if you could help please as I'm sure I must be doing something wrong.

I have a project which is hosted on a private GitLab and use Jira for issues which is hosted elsewhere. Regardless of what I've tried, the issue tracker link is always set to eg. `http://git@foo.local:group/project/issues/1234` – a strange hybrid of `repository.url`.

The notable parts of my package.json are below;

```json
{
  "bugs": {
    "url": "https://foo.jira.com/browse-3/"
  },
  "config": {
    "commitizen": {
      "path": "./node_modules/cz-conventional-changelog"
    },
    "ghooks": {
      "commit-msg": "validate-commit-msg"
    }
  },
  "devDependencies": {
    "cz-conventional-changelog": "1.1.6",
    "validate-commit-msg": "2.6.1",
    "standard-version": "2.3.0"
  },
  "issue": "https://foo.jira.com/browse-1/",
  "issues": "https://foo.jira.com/browse-2/",
  "repository": {
    "type": "git",
    "url": "git@foo.local:group/project.git"
  },
  "scripts": {
    "release": "standard-version"
  }
}
```

**Comment by stevemao** [comment]
The angular preset is not using the `bugs` entry. It parses the `repository.url` and get the base url, then append with `commits` etc. The benefit of this is that you could reference issues from another user's repo.

**Comment by stevemao** [comment]
> http://git@foo.local:group/project/issues/1234 – a strange hybrid of repository.url.

Sorry, I misunderstood.
I will test the url against [get-pkg-repo](https://github.com/stevemao/get-pkg-repo).

**Comment by JamieMason** [comment]
Thanks @stevemao, could you expand on "The benefit of this is that you could reference issues from another user's repo."? I didn't follow what you mean.

**Comment by stevemao** [comment]
Sorry, the idea of this module is meant to be opinionated so it cannot be configured. 

I was just trying to explain why it looks for `repository.url` instead of `bugs` entry.

How the current system works is something like this:
`host` + `user` + `repo` + `issue` + `issueNumber`

Because we have tools to get git hosted info so we can get a lot of useful information about the url. `user` here is not hard coded to the current project's user. So if you reference an issue of other repo, eg: `Closes otherUser/otherRepo#123`, it can link to that issue too. 

https://github.com/conventional-changelog/conventional-changelog-angular/blob/master/templates/commit.hbs#L26-L60

If we use the `bugs` entry, we won't achieve this. We would have to do something like

`bugs` + `issueNumber`

We can't parse `bugs` url because it could be any arbitrary url.

**Comment by JamieMason** [comment]
Ahh now I see, you could commit a change which fixes a bug in a downstream project. Makes sense.

Thanks a lot for your help.

**Comment by bcoe** [comment]
@JamieMason @stevemao, it would be interesting to support git lab and perhaps bitbucket -- I wonder if we could abstract the issue and at mention logic behind a wrapper that supports a few other hosted git services.

@JamieMason perhaps open an issue along these lines?

**Comment by Tapppi** [comment]
@bcoe @JamieMason That sounds like a great idea, I would be interested in gitlab support for sure.

**Comment by stevemao** [comment]
> it would be interesting to support git lab and perhaps bitbucket

I opened an issue https://github.com/stevemao/get-pkg-repo/issues/7 (I haven't tested the url yet...)
As long as [hosted-git-info](https://github.com/npm/hosted-git-info) supports them, in fact, it does.

url: git@foo.local:group/project.git is actually an arbitrary url that's not being parsed properly...@JamieMason I bet if you do `npm repo` it won't open the correct page.

**Comment by JamieMason** [comment]
> url: git@foo.local:group/project.git is actually an arbitrary url that's not being parsed properly...@JamieMason I bet if you do npm repo it won't open the correct page.

I'd actually obscured the real url but went a bit far I think, more accurately it's `git@gitlab.foocorp-dev.local:retail/some-project.git` and testing `npm repo` just now seems to load the page in GitLab ok.

It's great that these new issues for GitLab and BitBucket have sprung from this one, but from @stevemao's https://github.com/conventional-changelog/standard-version/issues/48#issuecomment-224463858 I think my situation falls outside of the problem space standard-version wants to fill – and I respect that.

I have a project which does pretty much everything the conventional-changelog way, only our issue tracker is Jira and not GitHub/GitLab/BitBucket. I can make a little workaround that process CHANGELOG.md afterwards and does a find and replace or something.

Thanks a lot for your help and for making this really useful tool (I actually messed up btw and made a duplicate of this in https://github.com/JamieMason/commit-release without realising, I plan to use `standard-version` instead from now on.

**Comment by spudheadc** [comment]
For future reference you can use a postchangelog lifecycle hook to replace your github url with your jira url.

Something along the line of

"standard-version": {
    "scripts": {
      "postchangelog": "replace '<<MY GITHUB URL>>' '<<MY JIRA URL>>' CHANGELOG.md"
    }
  }
