### ISSUE TITLE
Is it possible to disable the link to the changes?

### ISSUE THREAD

**Issue by averb** [conventional-changelog/standard-version#481]
Hi!
I want to turn off these links from the CHANGELOG.md

![image](https://user-images.githubusercontent.com/6570036/68672502-6e109f00-055a-11ea-82f2-c61da907117b.png)

Could you help me guys?

**Comment by scallacs** [comment]
Hi,

I had the same question, I'm adding an answer for the followings.

You can at remove the links with context option `linkReferences`. 
 `conventional-changelog ... --context config.js` and`config.js`:

``` 
module.exports = {
    linkReferences: false
};
```

To remove commit hash completly you will have to create a custom preset.

**Comment by averb** [comment]
thanks a lot @scallacs
