### ISSUE TITLE
Cannot skip tag prefix

### ISSUE THREAD

**Issue by gultyaev** [conventional-changelog/standard-version#490]
I need tags to be simple numbers.
According to docs I need to pass `-t` flag to skip tags when no value provided.

However, when I run `release:d` I have created tag with `v` prefix.

package.json excerpt
```
...
"scripts": {
  ...
  "release": "standard-version",
  "release:d": "standard-version -- -t"
}, 
"devDependencies": {
  ...,
  "standard-version": "^7.0.1",
}
```

```
node -v
v12.13.1
```

![image](https://user-images.githubusercontent.com/22374911/69619519-56e6ac80-1044-11ea-8e92-64e33e9bd7d9.png)

**Comment by Laruxo** [comment]
`standard-version --tag-prefix=` works for me.

**Comment by gultyaev** [comment]
Well it works, but in README it's said that `If you do not want to have any tag prefix you can use the -t flag without value.`. I've tried that. Even tried `npx standard-version -t` but that still added `v` to my tag name

**Comment by CoderAFI** [comment]
@gultyaev the same question. did you have solved it ?

**Comment by jorenbroekema** [comment]
Yeah this is a bug or at least a mistake in the documentation. 

The `-t` / `--tag-prefix` flag is **not a boolean flag**. It is a string type. So if you pass nothing, it will fallback to the default value `v`. So you need to be explicit about the value.

Either:
```sh
standard-version -t ""
```

or
 
```sh
standard-version --tag-prefix ""
```

or

```sh
standard-version --tag-prefix=
```

I ran into this a couple of times before I figured out the problem, also thanks to @Laruxo 's comment
