### ISSUE TITLE
Tests fail on windows with JScript compilation errors

### ISSUE THREAD

**Issue by Tapppi** [conventional-changelog/standard-version#50]
`npm t` never even gets to any work on Windows due to a `Microsoft JScript compilation error` being thrown during each test case.

**Comment by Tapppi** [comment]
Tests now run, but there seems to be a bug overwriting the projects package.json and CHANGELOG.md with test data after running ALL tests.. If i ctrl-c out of the tests midway through tit doesn't happen. Working on it though.

**Comment by bcoe** [comment]
@Tapppi interesting, this could be a path bug ... perhaps we're screwing up `path.sep` or something along these lines?

**Comment by Tapppi** [comment]
@bcoe Issue #51 for it, I got it fixed already though, I'm creating pull requests for all windows fixes (#49, #51 and this) now.
