### ISSUE TITLE
bumpfiles example uses "file" not "filename"

### ISSUE THREAD

**Issue by mtfurlan** [conventional-changelog/standard-version#504]
In the [Can I use standard-version for additional metadata files, languages or version files?](https://github.com/conventional-changelog/standard-version#can-i-use-standard-version-for-additional-metadata-files-languages-or-version-files) section of the README the `.versionrc` example uses `file` instead of `filename`.

I installed standard-version with `npm i -g standard-version@next` and have version `7.1.0`.

When the `.versionrc` refers to `file`, it prints this and returns 1.
```
The "path" argument must be of type string. Received type undefined
```

**Comment by jbottigliero** [comment]
Hi, we've updated the documentation to reflect the proper attribute – thanks!

**Comment by thattomperson** [comment]
Hey, This is still incorrect in the readme on https://www.npmjs.com/package/standard-version
is there some other step to update the readme on there?
