### ISSUE TITLE
Cannot bump files with custom updater

### ISSUE THREAD

**Issue by gultyaev** [conventional-changelog/standard-version#507]
config-init.updater.js
```
module.exports.readVersion = function(contents) {
    console.log('read file', contents.slice(30));
    const version = contents.match(/(?<=static version = ')(.*)(?=';)/g)[0];
    console.log('return version', version);
    return version;
};

module.exports.writeVersion = function(contents, version) {
    console.log('write file', contents.slice(30));
    return contents.replace(/(?<=static version = ')(.*)(?=';)/g, () => {
        console.log('replace version with', version);
        return version;
    });
};
```

package.json
```
{
...
    "standard-version": {
        "bumpFiles": [
            {
                "file": "projects/.../my.service.ts",
                "updater": "config-init.updater.js"
            }
        ]
    }
}
```

Node version v12.13.1
"standard-version": "^7.0.1"

When I run `npx standard-version --tag-prefix= --dry-run` I get an output
```
✔ bumping version in package.json from 10.1.1 to 10.2.0
✔ bumping version in package-lock.json from 10.1.1 to 10.2.0
✔ outputting changes to CHANGELOG.md

.. changelog ...
✔ committing package-lock.json and package.json and CHANGELOG.md
✔ tagging release 10.2.0
ℹ Run `git push --follow-tags origin master` to publish
```

No mention of bumping my file that I've specified in bumpFiles. 
How can this be fixed or replaced with my own file resolver if it doesn't support TypeScript files?

For now I'm forced to workaround this with posttag script which replaces version with current tag. Removes tag. Commits changed file and creates tag on HEAD with deleted value which isn't a straightforward solution and kind of pollutes commit history

**Comment by tommywo** [comment]
updaters were introduces in 7.1.0, which wasn't yet promoted to latest
so try `npx standard-version@next --tag-prefix= --dry-run`
