### ISSUE TITLE
I did it like this:

### ISSUE THREAD

**Issue by perfectlyimaginary** [conventional-changelog/standard-version#513]
I did it like this:
```
  "standard-version": {
    "changelogHeader": "---",
    "scripts": {
      "prechangelog": "rm CHANGELOG.md"
    }
  }
```

_Originally posted by @Laruxo in https://github.com/conventional-changelog/standard-version/issues/487#issuecomment-559511305_

**Comment by jbottigliero** [comment]
It looks like this PR might have been opened by accident and was originally intended to be a comment on _another_ PR.

If you do have an issue or feature request, please consider adding more context to both the title and description and reopening. 

Thanks! ✌️
