### ISSUE TITLE
Different set of script depending on `prerelease`

### ISSUE THREAD

**Issue by nolde** [conventional-changelog/standard-version#522]
This is a new feature request.

What about having a different set of scripts (or even full config) depending on whether the `--prerelease` flag was used? That would allow better granularity of behaviour with low impact to existing code.

Example:
```
{
  "standard-version": {
    "prerelease": {
      "scripts": {
        "postbump": "npm run deploy -- --stage staging"
      }
    },
    "scripts": {
      "postbump": "npm run deploy -- --stage production"
    }
  }
}
```
It could be also `prereleaseScripts` instead of `prerelease.scripts`. The idea is to allow better usage of the prerelease functionality.

**Comment by jbottigliero** [comment]
Thanks for the request! Rather than expanding on the configuration would your use case be solved if `standard-version` provided the version to the `postbump` script as an argument? Taking a look at the lifecycles it seems like they might benefit from having some context...

**Comment by nolde** [comment]
Thanks for considering it. The ability of being able to switch behaviour depending on context would be highly beneficial. It could even be passing a different config file in, instead of the default `.versionrc` file. A simple option, with low impact, would make it a lot more flexible.

**Comment by nolde** [comment]
Actually, forget it. As you offer a `.versionrc.js`, I can fully customise it myself, I just need more of my own code involved.

Keep it simple on your side, it makes more sense.
