### ISSUE TITLE
Unable to use new "bumpFiles", "packageFiles" and "updaters" (Publish standard-version@7.1.0 to NPM Registry as "latest")

### ISSUE THREAD

**Issue by jbottigliero** [conventional-changelog/standard-version#531]
It looks like we haven't marked `7.1.0` as the `latest` release (still `next`). This is causing some issues with folks expecting to use the new [bumpFiles, packageFiles and updaters](  https://github.com/conventional-changelog/standard-version#bumpfiles-packagefiles-and-updaters).

- [x] Publish `standard-version@7.1.0` as `latest` on the NPM registry

**Workaround**: Use/Reference `standard-version@next` or update your `package.json` version syntax to explicitly require >= 7.1.0 (ie. `"standard-version": "^7.1.0"`)

https://www.npmjs.com/package/standard-version

**Comment by tommywo** [comment]
standard-version@7.1.0 is promoted to latest 🎉 
thank you @jbottigliero
