### ISSUE TITLE
Changelog is overrided instead of append

### ISSUE THREAD

**Issue by FixRM** [conventional-changelog/standard-version#532]
Hi there! May be I miss something or simply doesn't understand how this tool should work.

Version 7.1.0 

My scenario:
1. run standard-version
2. CHANGELOG.md is created
3. I manually change header and description
4. I manualy commit this change as a fix: 
5. run standard-version again

Expected: standard-version should append history and keep my header and description
Actual: header and description are overrided by default values.

I thought it was working in different way when I was using it previously on other project. If not how can I provide template? I see some header customization options but what about description part?

**Comment by tommywo** [comment]
I believe you should amend the commit created by standard-version instead of making a new commit and running standard-version again.

**Comment by FixRM** [comment]
Thanks @tommywo! It's a good idea, I missed that. But I guess it doesn't solve my problem?

**Comment by tommywo** [comment]
Can you tell what did you mean by `I manually change header and description` ?
Example would be useful.

**Comment by FixRM** [comment]
@tommywo, sure. I got the following CHANGLOG.md generated:

```
# Changelog

All notable changes to this project will be documented in this file. See [standard-version](https://github.com/conventional-changelog/standard-version) for commit guidelines.
```
I change it to be:

```
#What's new

And it is awesome! 
```

**Comment by tommywo** [comment]
Header is overwritten by design. You can change it using flags by running
`standard-version --header="# What's new\n\nAnd it is awesome!"`. It should be also possible to set it in `.versionrc` or `package.json` file.

**Comment by FixRM** [comment]
Thanks, @tommywo. I thought it was working in different way.
