### ISSUE TITLE
Question: any way to change the definition of major/minor/patch?

### ISSUE THREAD

**Issue by kesun** [conventional-changelog/standard-version#536]
In our release rituals, we reserve the patch spot for hotfix versioning. Major release versions happen very rarely and are determined on a case-by-case basis manually. So everything should be treated as a minor release, until otherwise specified.

So if there a way to configure the standard-version so it'll automatically treat all commit types as a minor?

**Comment by Jafferwaffer** [comment]
Why even use standard-version at this point?
You can just do `npm version minor`

**Comment by kesun** [comment]
Very good point...! Thank you!
