### ISSUE TITLE
standard-version@8 drops support for NodeJS@8 (without mention in CHANGELOG)

### ISSUE THREAD

**Issue by jbottigliero** [conventional-changelog/standard-version#549]
By updating to `semver@7` (#508) we've dropped support for NodeJS@8.

We actually haven't tagged (or published a release) in some time and it seems like we _could_ potentially revert #508  and cut a minor _before_ doing the upgrade.

It's also worth mentioning that `conventional-changelog` just dropped support for NodeJS@8 on `master` (conventional-changelog/conventional-changelog#599)

**Comment by nihalgonsalves** [comment]
I suppose this should be renamed to `9.x.x drops support for NodeJS@8`?

**Comment by jbottigliero** [comment]
Yup! This ticket is probably no longer necessary. I'm going to change the title, close the ticket and add a few details for posterity.

---

- `standard-version@9` **officially** drops support for `NodeJS@8`, this breaking change is listed in the changelog.
- **If you are using a version of `standard-version > 7.1, <= 8` on NodeJS@8**, you _may_ encounter issues based on a dependency update (2f04ac8fc1c134a1981c23a093d4eece77d0bbb9). Downgrading to `7.1.0`, or using a hash before this change would likely be your best option for compatibility.
