### ISSUE TITLE
compareUrlFormat is not working in Github Actions

### ISSUE THREAD

**Issue by ioannisGiak89** [conventional-changelog/standard-version#599]
Hi there,

We just came across an issue with compareUrlFormat.

Although everything is working fine on local machine when we are trying to bumb the version on a github action in CI, the compare url for the tags is not populated.

After a lot of tries we figured out that the `{{previousTag}}` is not available. 

All the other URLs (issueUrlFormat, commitUrlFormat etc) are working properly.

Any ideas why this could happen?

**Comment by ioannisGiak89** [comment]
We solved this. Just in case that someone has the same issue, it had to do with the way we checkout the project in the Github Actions. We are using https://github.com/actions/checkout and you need to set `fetch-depth: 0` to get the tag history otherwise you it only fetches the branch.

**Comment by mikaelrss** [comment]
> We solved this. Just in case that someone has the same issue, it had to do with the way we checkout the project in the Github Actions. We are using https://github.com/actions/checkout and you need to set `fetch-depth: 0` to get the tag history otherwise you it only fetches the branch.

Thanks! Had the same issue, and this solved our problem as well.
