### ISSUE TITLE
Ignore commits before X

### ISSUE THREAD

**Issue by davidsneighbour** [conventional-changelog/standard-version#601]
I am starting to use `standard-version` with my repository that has lots of commits over 5+ years. I would like to ignore "everything before yyyy-mm-dd" in my initial run to keep the changelog readable and small. If I run `standard-version` without any parameters it will create an extremely long changelog with commits that I do not remember (as in they probably were done a year or longer ago). Is there a way to start from "NOW" to create the changelog?

Is there a way to create multiple changelogs based on time or major version constraints?

**Comment by davidsneighbour** [comment]
To clarify, those old commits end up in the current version notices, not somewhere down the file. I run `standard-version`, it creates a new version and add all the commits under the new version, then some tags that I did before. I would expect it to ignore commits from untagged versions or put them under the last (first in time) tag in the changelog.

**Comment by tbarlow12** [comment]
@davidsneighbour how did you resolve this issue?

**Comment by jiangtao** [comment]
what's the solution?
