### ISSUE TITLE
How can I tell standard-version to commit more files?

### ISSUE THREAD

**Issue by jcornaz** [conventional-changelog/standard-version#646]
Hi, 

In a `postbump` script I use `sed` to replace some references in documentation and readme.

But theses files are not commited by `standard-version` and I have to manually amend the commit (and move the tag).

Can I configure `standard-version` to commit those file?

**Comment by stroym** [comment]
Seems like you're looking for the -a/--commit-all switch. (For more information type `standard-version -h` into your terminal.)
~~I'm not sure how exactly it would interact with postbump, so you might have to do something like this:

`standard-version --skip.commit --skip.tag
git add . / git add -A
standard-version --skip.changelog --skip.bump`

I personally do pretty much that, but my usecase is quite different.~~

On second thought, just adding `git add . / git add -A` to your postbump script and using the -a switch with standard-version should be enough in your case.

**Comment by jcornaz** [comment]
Great thanks.
