### ISSUE TITLE
Tags via git-semver-tags not working  

### ISSUE THREAD

**Issue by gtokman** [conventional-changelog/standard-version#672]
I started versioning my project using semantic versioning via conventional commits and standard version. When standard version generates the diff between versions it runs a command similar to `npx git-semver-tags --tag-prefix v` to fetch tags, then compares the previous tag with the new one created. 

I am struggling to figure out why `npx git-semver-tags --tag-prefix v` is not fetching all the tags on my project repository. For example in GH, I see all my tags v4.10.0, v4.10.1... etc but when running the command locally I only see one tag v4.10.0. Did I tag v4.10.0 a certain way that I didn't the others? How does `semver-tags` fetch these from the GH repository, because running ` git tag -l |grep v` lists all of them but the former command does not. Any insight will be appreciated.

Running  `git tag -l |grep v`
```
v4.10.0
v4.11.1
v4.11.2
v4.11.3
v4.11.4
v4.11.5
v4.11.6
v4.12.0
v4.12.1
v4.12.2
```

Running `npx git-semver-tags --tag-prefix v`
```
v4.10.0
```

**Comment by ivanfuzuli** [comment]
Same here, did you found a solution? @gtokman
