### ISSUE TITLE
Changing currentTag value when using standard-version

### ISSUE THREAD

**Issue by canserkanuren** [conventional-changelog/standard-version#676]
Hello,

Like the subject says, is it possible to define a specific message tag when using standard-version ? The same way we can specify a specific release commit message format, by using `releaseCommitMessageFormat` in `.versionrc`.

Thank you for your time.

**Comment by eiriarte-mendez** [comment]
Hi @canserkanuren , did you saw here:
https://github.com/conventional-changelog/conventional-changelog-config-spec/blob/master/versions/2.1.0/README.md#releasecommitmessageformat-string

BTW you can also try (in `versionrc.json`):
```json
"tagPrefix": "v-"
```

**Comment by canserkanuren** [comment]
Hello, it seems to be working!
I will close this issue. Thanks again!
