### ISSUE TITLE
Standard version isn't bumping correctly for me anymore.

### ISSUE THREAD

**Issue by kpham007** [conventional-changelog/standard-version#685]
**Describe the bug**
Standard version isn't bumping correctly for me anymore.  I have a repo setup at https://github.com/kpham007/standard-version-test/commits/main.  If you notice the commit messages have the "fix:" scope in them but when I use standard-version, it keeps bumping the minor version.

**Current behavior**
The commit messages have the "fix:" scope but when I use standard-version, it bumps the minor version instead of the patch version.  Even standard-version --dry-run will also do an incorrect bump.

**Expected behavior**
The version should bump correctly based on the scope in the commit message: fix should bump patch, feat should bump minor, and breaking changes should bump major.

**Environment**
- `standard-version` version(s): 9.0.0
- Node/npm version: Node v12.18.3 / npm v6.14.6
- OS: OSX 11.0.1

**Possible Solution**

**Additional context**
This has worked before without issues.  I haven't changed the way I've run commands either.  Is there something I may be missing?

**Comment by kpham007** [comment]
Nevermind.  I figured it out.  I need to push git tags as well.

**Comment by DuncanFaulkner** [comment]
@kpham007 what was the answer, I have an issue where it doesn't bump correctly and I have to specify patch, minor, major. The other issue I have is the changelog seems to repeat a large section every time

**Comment by kpham007** [comment]
Actually I'm still running into issues.  I noticed if I did the following, it seems to work fine and bumps the patch version.
`standard-version --first-release
standard-version --dry-run`

If I do the following, it bumps the minor version.  The reason I'm adding a custom tag is that it's a monorepo with different npm packages that I need to build.  The tag seems to cause it to behave differently.
`standard-version --first-release -t test\@
standard-version --dry-run`

If I actually commit changes and do a test with just the `fix:` scope, it'll always continue to bump the minor version.

**Comment by DuncanFaulkner** [comment]
I use a monorepo, but for an application no libraries. plus I have to stage changes, write commit message (using comittizen) call npm run release:patch (or minor), edit the changelog as this keeps pulling in old changelog messages, then do a git add and git amend to include version and changelog then push to gitlab, right pain.

**Comment by trouba** [comment]
@kpham007 Do you use an annotated tag ? 

Standard-version uses the last annotated tag to create the new tag, you can check it with `git describe`. 

You can also get all tags with `git tag -l` and check if a tag is annotated with 'git show <tag>'. If you see a tag section before the commit section it's an annotated tag.

More info: https://stackoverflow.com/questions/1404796/how-to-get-the-latest-tag-name-in-current-branch-in-git

**Comment by kpham007** [comment]
Sorry I haven't gotten back to this but yes I think I had to make sure there were annotated tags first.  I believe I ended up pushing or fixing the tags and once those were there, it started working for me.  I haven't had any issues since.

**Comment by JeanOsorio** [comment]
I have the same problem but I don't understand the solution of @trouba. Would you explain a little more how can I fix this problem, because no matter the type of commit standard version is always pump the minor

**Comment by lordfpx** [comment]
Same problem here, `npm run release -- --release-as minor` bump tag like a patch :-(
