### ISSUE TITLE
How do I insert changelog message into commit message?

### ISSUE THREAD

**Issue by kimnh-0823** [conventional-changelog/standard-version#692]
When I using `standard-version` to create a new release, `standard-version` will auto-create a new commit:
```
chore(release): 1.0.0-beta.2
```

How does it create a commit message with Changelog? For example:

```
chore(release): 1.0.0-beta.2

### Features

* Feature A
* Feature B

### Bug Fixes

- Bug A
- Bug B
```

Anyone here for help?

**Comment by jbottigliero** [comment]
Hi @kimnh-0823 – the presence of additional messages in your changelog is dependent on your usage of the [Coventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) syntax for your commits. To create your example changelog your `git log` before running `standard-version` would have to look something like:

```
commit <HASH> (origin/dev, origin/HEAD, dev)
Author: <Author>
Date:   <Date>

    feat: Feature A

commit <HASH>
Author: <Author>
Date:   <Date>

    fix: Bug B

commit <HASH>
Author: <Author>
Date:   <Date>

    feat: Feature B

commit <HASH>
Author: <Author>
Date:   <Date>

    fix: Bug A

commit <HASH>
Author: <Author>
Date:   <Date>

    chore(release): 1.0.0-beta.1
```


Hopefully, that answers your question – feel free to follow-up if not!

**Comment by kimnh-0823** [comment]
@jbottigliero Thanks for your support.

Currently, the changelog is already rendered by `standard-version` and saved into the `CHANGELOG.md` file successfully.
But I also expect the changelog will be saved in the release's commit message. Not only in the `CHANGELOG.md` file.

```
---- Current commit:
chore(release): 1.0.0-beta.1

---- Expect commit:
chore(release): 1.0.0-beta.2

### Features
* Feature A...
* Feature B...

### Bug Fixes

- Bug A...
- Bug B...
```

**Comment by jbottigliero** [comment]
I see – sorry for the misunderstanding! This isn't something that is supported at the moment. We allow for altering the formatting for the release commit message (`--releaseCommitMessageFormat`), but the new version is the only value provided to this template. 

As an alternative to the commit message, there are [releaser-tools](https://github.com/conventional-changelog/releaser-tools) that will include the changelog as part of a tagged release (ie. https://github.com/conventional-changelog/standard-version/releases/tag/v9.0.0).

**Comment by jbottigliero** [comment]
I'm going to close this issue.  If the releasers wind up not working for you feel free to comment and we can move this to a feature request. Thanks!
