### ISSUE TITLE
automated gitlab releases

### ISSUE THREAD

**Issue by Lueton** [conventional-changelog/standard-version#694]
Hey folks,

does anyone have any idea how to use standard-version to automatically create releases in Gitlab with Gitlab CI?

**Comment by jbottigliero** [comment]
Hey @Lueton – `standard-version` won't handle this aspect of release management. An option in the `conventional-changelog` ecosystem would be to use the [`conventional-gitlab-releaser`](https://github.com/conventional-changelog/releaser-tools/tree/master/packages/conventional-gitlab-releaser).

If you check out the [Recommended Workflow](https://github.com/conventional-changelog/releaser-tools/tree/master/packages/conventional-gitlab-releaser#recommended-workflow) section, `standard-version` will take care of 1-6 for you, so at that point, it's just a matter of triggering the releaser. I haven't worked with the GitLab releaser personally, but I have success with the GitHub variant with a very similar workflow.

**Comment by Lueton** [comment]
@jbottigliero Thank you very much!
