### ISSUE TITLE
merge with standard-changelog

### ISSUE THREAD

**Issue by bcoe** [conventional-changelog/standard-version#7]
@stevemao @nexdrew based on our conversation in:

https://github.com/conventional-changelog/meta/issues/1

Should we merge some of this functionality into `standard-changelog` and retire this repo?

**Comment by stevemao** [comment]
I don't have a strong opinion on this :) Maybe `conventional-recommended-workflow` can do other interesting combination of tools around `conventional-changelog`. EG: a wrapper of `standard-changelog` with `conventional-github-releaser`. Just a thought.

> and standard-changelog was a bin just applied the whole recommended flow:

I don't mind your original proposal either..

**Comment by bcoe** [comment]
I think we've figured this out:

* `standard-version`: replaces `npm version` with `conventional-changelog`.
* `standard-changelog`: generates a changelog for you.
