### ISSUE TITLE
noisy output when "fixes #" syntax used in pull request

### ISSUE THREAD

**Issue by bcoe** [conventional-changelog/standard-version#70]
The output of the CHANGELOG template is pretty noisy when someone specifies that a pull request closes issues (see https://github.com/istanbuljs/babel-plugin-istanbul/blob/master/CHANGELOG.md#bug-fixes).

`take realpath of process.cwd(), fixes #7 (#8) (e8d3785), closes #7 #8`

Maybe if we moved `(#8) (e8d3785)` to the end of the line? not quite sure what would make this read better.

thoughts? @nexdrew, @Tapppi, @stevemao

**Comment by nexdrew** [comment]
So, to be clear:

- `take realpath of process.cwd(), fixes #7 (#8)` comes from the squashed-merged commit message
- ` (e8d3785), closes #7 #8` comes from the [`conventional-changelog-angular` commit template](https://github.com/conventional-changelog/conventional-changelog-angular/blob/v1.2.0/templates/commit.hbs#L28)

Seems like we should just ignore the issue/PR references if links are already included in the commit message, no?

**Comment by Tapppi** [comment]
Agree with @nexdrew, I see no reason for two links if the reference is already there.

**Comment by stevemao** [comment]
Originally the angular convention doesn't contain `(#8)` at the end of the header. They use `Closes #8` to close an issue. Looks like they might change it. We should change it accordingly.

**Comment by Tapppi** [comment]
Yeah, the angular convention expects issue refs in the footer, e.g. "Closes #x". If the refs are already in the header, do we want to still include the additional ", closes ##x " in the changelog?

**Comment by stevemao** [comment]
Maybe not. TBH I don't like to hardcode the verb `closes`, it should use the same verb in the commit message (so it could be `fixes`, `resolves` etc).

**Comment by nexdrew** [comment]
The Angular convention existed before GitHub's squash-and-merge feature, but the squash-and-merge is really what makes `standard-version` compelling. I think this tool should work best with the defaults used by squash-and-merge rather than exact Angular compliance.
