### ISSUE TITLE
Bumbing Existing Named Prerelease Versions not working

### ISSUE THREAD

**Issue by dawidchar** [conventional-changelog/standard-version#700]
**Describe the bug**
When attempting to bump an already created/existing named prerelease such as dev, bumping that same prerelease does not update the version of that prerelease
`standard-version --prerelease dev`

**Current behavior**
from 1.0.1-dev.0 to 1.0.1-dev.0

**Expected behavior**
from 1.0.1-dev.0 to 1.0.1-dev.1

**Environment**
- `standard-version` version(s): 9.1.0
- Node/npm version: Node 10.23.0 / npm 6.14.8
- OS: Windows 10

**Comment by dawidchar** [comment]
Everything works, 

I added Bumb files in the .versionrc but not packagefiles and that made it not work, adding packagefiles in the config seems to have fixed the issue

**Comment by bcoe** [comment]
@dawidchar is there anything we can document better, or that could have helped avoid this hiccup?

**Comment by dawidchar** [comment]
This part of the documentation helped me realise the error 

> User-defined files where versions should be "bumped", but not explicitly read from

What I'm guessing was happening was it was reading the version from some other place by default, correct me if I'm wrong but I think the documentation said it reads it from git, maybe a simple log saying falling back to reading version from git/somewhere else could be useful
