### ISSUE TITLE
Should it create the latest tag?

### ISSUE THREAD

**Issue by tleunen** [conventional-changelog/standard-version#72]
I wonder if `standard-version` should also set the latest tag when it defines the new tag.

Maybe with a specific option?

`semantic-release` sets the tag so I was expecting `standard-version` to do the same.

**Comment by stevemao** [comment]
It does, which is said on the readme:
> tags a new release

Or are you talking about something else?

**Comment by bcoe** [comment]
@tleunen would love to have parity with semantic-release. Does the `latest` tag just point at whatever version was most recently tagged? want to take a stab at implementing this?

**Comment by tleunen** [comment]
Sorry if it wasn't clear, yes I'm talking about the `latest` tag, not tagging a new release.

And yes I believe it's done automatically with semantic-release because they use the github API to create a true release, not just creating a version tag. (see https://developer.github.com/v3/repos/releases/#create-a-release)
We could "simulate" the behavior by forcing the latest tag I guess, using sth like `git tag latest -f`

**Comment by nexdrew** [comment]
Correct me if I'm wrong, but the concept of a release only exists in GitHub (or in the npm registry), not in the git repo itself. `standard-version` deliberately doesn't talk to any remote resources; it only makes changes to the local git repo.

Wouldn't a "latest tag" only exist in GitHub or npm? Is it an actual tag in the git repo itself?

**Comment by tleunen** [comment]
> Wouldn't a "latest tag" only exist in GitHub or npm? Is it an actual tag in the git repo itself?

Hmm.. Seems you're right. From the [npm doc](https://docs.npmjs.com/cli/tag):
> Publishing a package always sets the "latest" tag to the published version.

Sorry, I thought the latest release from github was linked to the "tag", but it's not.

**Comment by nexdrew** [comment]
@tleunen No worries, it's a good idea, it's just outside the scope of this tool is all. Both GitHub and npm point a "latest" release at a specific version, and in GitHub it points to a version-specific tag in the repo.

You might want to check out the `np` tool by Sindre Sorhus and team. I'm not sure if it specifically uses the GitHub API to create releases there, but it does push/publish the next version. Unfortunately it doesn't have the nice auto versioning and changelog generation of `standard-version`, and as of yet I've failed to convince them otherwise, but I'm toying with the idea of building a wrapper that combines the two. Would that be of interest to you?

**Comment by Tapppi** [comment]
@nexdrew slightly off-topic, have you talked to them (sindre & co.) about allowing a configurable version command in `np`? I've been meaning on to open an issue, since it seems really interesting to me.

**Comment by tleunen** [comment]
Having something in between `standard-version` and `np` could be nice. But at the same time, I like the fact that I can "review" the version the tool gives me, in case there's an error for some reasons...

So I guess it would require a `np` without the version bump step.

**Comment by nexdrew** [comment]
@Tapppi I asked them about their thoughts on integrating the tools/ideas (read about that here https://github.com/sindresorhus/boxen/pull/11#issuecomment-224058027) but Sindre was not interested. I did not explicitly ask about customizing the version command in np - which is a good idea.

Looks like @bcoe just created an issue for further discussion though. ;)
