### ISSUE TITLE
How can I get `v1.2.3-hotfix.1` instead of `v1.2.3-hotfix.0`

### ISSUE THREAD

**Issue by edzis** [conventional-changelog/standard-version#722]
When I am on version `v1.2.3` and run `standard-version --prerelease hotfix` I get `0` as the build number.
That adds confusion when communicating hotfix versions with colleagues.

**Comment by jbottigliero** [comment]
There isn't a way to make this happen through `standard-version` configuration. We have the `--release-as=` flag, but my guess is that would be too manual for your use case.

One option would be to bump your package twice, using `--skip` to avoid lifecycles based on your specific needs.

```bash
% standard-version --prerelease --skip.commit --skip.tag --skip.changelog
✔ bumping version in package.json from 1.0.0 to 1.1.0-0
% standard-version --prerelease --skip.tag                               
✔ bumping version in package.json from 1.1.0-0 to 1.1.0-1
✔ created CHANGELOG.md
✔ outputting changes to CHANGELOG.md
✔ committing package.json and CHANGELOG.md
```

**Comment by edzis** [comment]
Thanks for the suggestion @jbottigliero!
