### ISSUE TITLE
{ "packages": { "": { "version": "1.0.0" } } } in package-lock.json isn't bumped

### ISSUE THREAD

**Issue by regseb** [conventional-changelog/standard-version#732]
**Describe the bug**
`{ "packages": { "": { "version": "1.0.0" } } }` in _package-lock.json_ isn't bumped.

**Current behavior**
`{ "packages": { "": { "version": "1.0.0" } } }` in _package-lock.json_ is unchanged.

**Expected behavior**
Bump `{ "packages": { "": { "version": "1.0.0" } } }` in _package-lock.json_.

**Environment**
- `standard-version` version(s): v9.1.1
- Node/npm version: Node 14.16.0 / npm 7.6.1
- OS: Ubuntu 20.04.2 LTS

**Possible Solution**
Search for the property and if it exists: update the value.

**Additional context**
This property was probably added in [`lockfileVersion`](https://docs.npmjs.com/cli/v7/configuring-npm/package-lock-json#lockfileversion) _2_ with _npm v7_.

**Steps to reproduce this issue**
```shell
git init
npm init
npm install standard-version --save-dev
git add package.json package-lock.json
git commit -m "foo"
npx standard-version
head package-lock.json
```
```json
{
  "name": "testcase",
  "version": "1.0.1",
  "lockfileVersion": 2,
  "requires": true,
  "packages": {
    "": {
      "version": "1.0.0",
      "license": "ISC",
      "devDependencies": {
```
```shell
npm install
head package-lock.json
```
```json
{
  "name": "testcase",
  "version": "1.0.1",
  "lockfileVersion": 2,
  "requires": true,
  "packages": {
    "": {
      "version": "1.0.1",
      "license": "ISC",
      "devDependencies": {
```

**Comment by MiniGod** [comment]
There's a PR for this: #713

**Comment by vicrep** [comment]
Closed by #713 and released as of v9.3.1 :)

**Comment by regseb** [comment]
I confirm that this issue is fixed in version _9.3.1_. @vicrep Thank you.

**Comment by mominafiz** [comment]
@vicrep  I was wondering why the package-lock.json is not bumped or excluded by standard-version. Even if updater is used in bumpFiles it doesn't do an update.

Maybe this issue was fixed and bug has re-appeared
