### ISSUE TITLE
Publish GitHub release notes?

### ISSUE THREAD

**Issue by JaKXz** [conventional-changelog/standard-version#74]
I'm not sure if this is even possible via the GitHub API but it would be cool if each tag / release automatically got the part of the changelog that pertains to it.

I'll try to look into this at some point unless someone else has the jump on me :)

**Comment by stevemao** [comment]
Have you tried semantic-release?

**Comment by stevemao** [comment]
Also conventional-github-releaser if you just want github releases

**Comment by JaKXz** [comment]
Yeah, https://github.com/conventional-changelog/conventional-github-releaser is what I was looking for. Thanks!

**Comment by medikoo** [comment]
If someone is after solution which reads release notes from `CHANGELOG.md` (as generated by standard-version) and pushes them to GitHub. I created https://github.com/medikoo/github-release-from-cc-changelog
