### ISSUE TITLE
Why is my changelog not generating, using self-hosted Gitlab?

### ISSUE THREAD

**Issue by DorkForce** [conventional-changelog/standard-version#740]
I'm trying to set this up for the first time, having learned of your package via [mokkapps blog](https://www.mokkapps.de/blog/how-to-automatically-generate-a-helpful-changelog-from-your-git-commit-messages/).  When I `npm run release`, the changelog only contains the next version such as (with no commits listed).

```
---
## 2.0.1-alpha (2021-04-07)
---
```

I have read through the documentation here twice, and here is my relevant configuration information:

**.versionrc.json**
```json
{
    "types": [
      {"type": "feat", "section": "Features"},
      {"type": "fix", "section": "Bug Fixes"},
      {"type": "chore", "hidden": true},
      {"type": "docs", "hidden": true},
      {"type": "style", "hidden": true},
      {"type": "refactor", "hidden": true},
      {"type": "perf", "hidden": true},
      {"type": "test", "hidden": true}
    ],
    "commitUrlFormat": "https://gitlab.myHost.com/myGroup/mySubgroup/myProject/-/commit/{{hash}}",
    "compareUrlFormat": "https://gitlab.myHost.com/myGroup/mySubgroup/myProject/-/compare/{{previousTag}}...{{currentTag}}",
    "issueUrlFormat": "https://gitlab.myHost.com/myGroup/mySubgroup/myProject/-/issues/{{id}}",
    "userUrlFormat": "https://gitlab.myHost.com/{{user}}"
  }
```

**package.json**
```json
{
    "name": "@itsme/theproject",
    "version": "2.0.0-beta.0",
    "repository": "https://gitlab.myHost.com/myGroup/mySubgroup/myProject/",
    "scripts": {
        "release": "standard-version"
    },
    "devDependencies": {
        "@commitlint/cli": "^12.0.1",
        "@commitlint/config-conventional": "^12.0.1",
        "husky": "^4.3.8",
        "standard-version": "^9.1.1",
    },
    "husky": {
        "hooks": {
            "commit-msg": "commitlint -E HUSKY_GIT_PARAMS"
        }
    }
}
```

Note, I am initiating standard-version via `npm run release -- --dry-run --release-as 2.0.1-alpha` (with or without dry-run), and (unrelated) it never seems to matter whether I try to skip the hooks or not (it is able to commit when I do not use dry-run), but this question is not about that.

Is there something obvious that I am missing?

**Comment by DorkForce** [comment]
MAyyyybe you could add a section for idiots like me who are testing without have any commits that aren't **hidden** 😆   Sorry for taking your time -- closing this up!

**Comment by bcoe** [comment]
@DorkForce folks make this mistake all the time, definitely a usability issue.

If you can think of where these docs would have jumped out at you, please feel free to submit a patch 👍

**Comment by DorkForce** [comment]
Ah yes, I shall do that!  Thanks!
