### ISSUE TITLE
How to specify initial package version?

### ISSUE THREAD

**Issue by d-ryzhikov** [conventional-changelog/standard-version#764]
Is it possible to specify the initial version different from `v1.0.0`. I haven't found a CLI-argument for this. I also tried specifying the version in the `composer.json`, specifying the `composer.json` in `packageFiles` and `bumpFiles` section, however it didn't work.

**Comment by jirayupiwon1** [comment]
> Is it possible to specify the initial version different from `v1.0.0`. I haven't found a CLI-argument for this. I also tried specifying the version in the `composer.json`, specifying the `composer.json` in `packageFiles` and `bumpFiles` section, however it didn't work.

**Comment by UnleashSpirit** [comment]
You can force version with `--release-as <version>`
https://github.com/conventional-changelog/standard-version#release-as-a-target-type-imperatively-npm-version-like

**Comment by d-ryzhikov** [comment]
Thank you, haven't noticed the description for this option.
