### ISSUE TITLE
DoS vulnerability from trim-newlines dependency

### ISSUE THREAD

**Issue by caioabe** [conventional-changelog/standard-version#765]
**Describe the bug**
Running Snyk tests, a vulnerability was found.

**Current behavior**
This causes our ci pipeline to break

**Expected behavior**
A bump of this library is needed

**Environment**
- `standard-version` version(s): 9.3.0
- Node/npm version: 14.15
- OS: node:14.15-alpine

**Possible Solution**
A bump of this library is needed

**Additional context**

![image](https://user-images.githubusercontent.com/6640404/120247425-be894380-c249-11eb-9fff-9341eb849bed.png)

**Comment by ollie-gopuff** [comment]
Why was this closed?

**Comment by MengRS** [comment]
@caioabe - I agree with @ollie-gopuff, can you let us know why this is closed? this is affecting us as well...

**Comment by MengRS** [comment]
@jirayupiwon1 - I'm confused... why did you reclose this with no comment? 

cc: @caioabe

**Comment by imagine10255** [comment]
Hi, 
add "trim-newlines": "4.0.2".
then `yarn install`


```
"devDependencies": {
    "cz-conventional-changelog": "3.3.0",
    "cz-customizable": "6.3.0",
    "standard-version": "9.3.0"
},
"resolutions": {
    "trim-newlines": "4.0.2"
}
```
