### ISSUE TITLE
How can I filter by scope?

### ISSUE THREAD

**Issue by sauldeleon** [conventional-changelog/standard-version#768]
Hello all, and first of all, thank you for this fantastic library!

We are using it in a monorepo with yarn workspaces, and we would love to generate multiple changelogs, one per package, just in case in a future we would separate in single repos.

I think this feature is not supported, or at least I have read nothing related with this in docs. But I think I can run the `standard-version` in each workspace, that will generate the changelog in that folder. with the skip tag option. Then I would bump this package version, and then increase main package.json version, as something in the inner packages has change.

So the flow would be something like

1. Execute command `yarn release:packageName` in root directory
2. This command runs standard version in the workspace like `yarn workspace packageName release`
3. In the `packageName`, the script would be something like `standard-version --skip tags` or maybe in config file, but it will bump version in the `packageName`.
4. The changelog in the `packageName` will include only commits related with a certain scope. So all commits in that scope are like `feat(pN)` `chore(pN)` ... etc
5. Finally this runs standard version in the root taking the commits with **no** scope (`feat:` `chore:` `whatever:`) bumping the version number only in the monorepo root directory, and creating a tag according to that bumped version, and will do a commit with all the changes

Well, this is my idea in my mind, but, is this possible with standard-version anyhow? I have seen that I can write the standard-version script as code mostly, 

```js
const standardVersion = require('standard-version')

// Options are the same as command line, except camelCase
// standardVersion returns a Promise
standardVersion({
  noVerify: true,
  infile: 'docs/CHANGELOG.md',
  silent: true
}).then((commits) => {
  // somehow I have the list of commit names here, to do filtering
}).then(() => {
  // standard-version is done
}).catch(err => {
    console.error(`standard-version failed with message: ${err.message}`)
})
```

but I dont know if I can get in the inside of how the scripts works to do this filtering, or maybe using the [lifecycle scripts](https://github.com/conventional-changelog/standard-version#lifecycle-scripts)

Sorry for the long post! any help or extra idea would be much appreciated!

**Comment by josteph** [comment]
Might be related with https://github.com/conventional-changelog/standard-version/issues/445, the proposed solution there worked for me.

**Comment by sauldeleon** [comment]
Hi @josteph 

Indeed, you are right! I will close this as I think is the same behaviour I was looking for. So I have tried #445 and it also worked.

But I have another new doubt. Should we upgrade the monorepo version number? or stick it to 0.0.0 forever? If for example we do any change in dependency versions, or add new scripts, should that be versioned too? or it does not have sense anymore?

Many thanks!
