### ISSUE TITLE
High severity vulnerability - Regular Expression Denial of Service

### ISSUE THREAD

**Issue by zacyang** [conventional-changelog/standard-version#772]
**Describe the bug**
npm i got unfixable issue
https://www.npmjs.com/advisories/1753

**Current behavior**
A clear and concise description of the behavior.

**Expected behavior**

**Environment**
- `standard-version` version(s): 9.3.0
- Node/npm version: [e.g. Node 10/npm 6]
- OS: [e.g. OSX 10.13.4, Windows 10]

**Possible Solution**
as https://www.npmjs.com/advisories/1753 suggest, Upgrade to versions 3.0.1 or 4.0.1 or later

**Additional context**
Add any other context about the problem here. Or a screenshot if applicable

**Comment by jorgexgb** [comment]
Im seeing this as well:
![image](https://user-images.githubusercontent.com/15152496/122634943-e5db6f80-d095-11eb-8ad1-0fbc56664c8b.png)

**Comment by h-enk** [comment]
Summarized /replay:

0. mkdir standard-version && cd standard-version
1. npm init -y
2. npm install standard-version -D


```bash

added 229 packages, and audited 230 packages in 10s

20 packages are looking for funding
  run `npm fund` for details

2 high severity vulnerabilities

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
```

```bash
# npm audit report

trim-newlines  <3.0.1 || =4.0.0
Severity: high
Regular Expression Denial of Service - https://npmjs.com/advisories/1753
fix available via `npm audit fix`
node_modules/get-pkg-repo/node_modules/trim-newlines
  meow  3.4.0 - 5.0.0
  Depends on vulnerable versions of trim-newlines
  node_modules/get-pkg-repo/node_modules/meow

2 high severity vulnerabilities

To address all issues, run:
  npm audit fix
```

Regular Expression Denial of Service - https://npmjs.com/advisories/1753

Update [sindresorhus/meow](https://github.com/sindresorhus/meow) in [conventional-changelog/get-pkg-repo](https://github.com/conventional-changelog/get-pkg-repo)?!

**Comment by golfovi** [comment]
Hello! I have found that vulnerability in several of my projects, is there a future update to fix it?

**Comment by jeanlescure** [comment]
Have literally hundreds of projects, both personal and commercial, where I use standard-version, giving me this high severity vulnerability including on Github.

The vulnerability comes from `trim-newlines`, which is a dependency of `meow`, which is a dependency of `standard-version`.

The latest versions of package `meow` have already updated the vulnerable package `trim-newlines`.

Now all that's missing is that `standard-version` updates the version of `meow` it depends on.

Is there an ETA on this?

**Comment by george-thomas-hill** [comment]
Bump.

**Comment by adamrossmusic** [comment]
bump x 2. Cybersec won't allow us to go prod.

**Comment by drazisil** [comment]
This appears to have been resolved as of https://github.com/conventional-changelog/get-pkg-repo/pull/62#issuecomment-892320204 and is stuck on a new package publish.

@stevemao, besides @hutson (who says they don't have publish access) you are the only other person on the package. Are you able to assist?

**Comment by BitForger** [comment]
bump

**Comment by vegarringdal** [comment]
bump

**Comment by nusairafnan** [comment]
bump

**Comment by spnq** [comment]
bump

**Comment by drazisil** [comment]
I believe this was fixed by this release 10 days ago. Has anyone checked since then?

**Comment by drazisil** [comment]
temp confused myself, sorry for the double comment.

I believe this may have been fixed by https://github.com/conventional-changelog/get-pkg-repo/runs/3551702198?check_suite_focus=true#step:8:8 10 days ago

I have not checked yet, has anyone else?

**Comment by bcoe** [comment]
This should have now been addressed:

```
+ standard-version@9.3.1
added 190 packages from 122 contributors and audited 190 packages in 6.851s

18 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

Please let me know if you do continue to have any issues.
