### ISSUE TITLE
How can we update CHANGELOG in dry-run

### ISSUE THREAD

**Issue by borisdamevin** [conventional-changelog/standard-version#777]
Can we update the `CHANGELOG.md` in `dry-run` mode?

For now this don't work.

Thank you.

**Comment by josteph** [comment]
Probably you don't need `--dry-run`? What's your use case?

**Comment by borisdamevin** [comment]
@josteph I wanna check `CHANGELOG.md` formating before any commit.

**Comment by josteph** [comment]
There is --skip.commit option that you can use.

**Comment by borisdamevin** [comment]
Yes, thank you!
