### ISSUE TITLE
Incorrect behavior in case when several project major versions maintained

### ISSUE THREAD

**Issue by s-panferov** [conventional-changelog/standard-version#78]
Hello. Thanks for the amazing library.

I have a small issue when `standard-version` bumps my versions incorrectly. After some investigation I've noticed that current version of `https://github.com/stevemao/git-latest-semver-tag` looks through *all the tags in the project sorted by time* to find the latest. This is incorrect, because of possible backports of fixes to the older versions.

This behaviour is already changed in the `master` branch of https://github.com/stevemao/git-latest-semver-tag, but the version is not published 😢 

@stevemao could you please publish it and bump `standard-version`?

**Comment by stevemao** [comment]
done
