### ISSUE TITLE
Can Dependabot use standard-version to bump version?

### ISSUE THREAD

**Issue by jrock2004** [conventional-changelog/standard-version#790]
So this might be more of a question for Dependabot but I would like when dependabot creates a PR to up something that when I close it, it updates the version and generates a log? Maybe this is a bad idea and there is something better to do?

**Comment by jbottigliero** [comment]
For this type of automation, you might want to look into https://github.com/googleapis/release-please and its GitHub Action integration. We've been using it as release management for _this_ package. In the example you've provided, after merging to your trunk release-please would open a release pull request ([example](https://github.com/conventional-changelog/standard-version/pull/836)) that you can merge when your read for a release to be cut.

You could piece the release-please behaviors from GitHub Actions (or CI-flavor of choice), Dependabot and `standard-version`, but that is a bit outside of the scope for this project.
