### ISSUE TITLE
Allow config param

### ISSUE THREAD

**Issue by thiagofelix** [conventional-changelog/standard-version#8]
Is there a reason to not accept the "config" param aside with the "preset"?

I am working with a completely custom commit format.

**Comment by stevemao** [comment]
The scope of this wrapper is not decided yet. But it'll be pretty opinionated which means you won't config too much. @thiagofelix You might wanna have a look at the lower level `conventional-changelog-cli`?

**Comment by thiagofelix** [comment]
I saw the ``conventional-changelog-cli`` as well as the others ``conventional-*`` packages, it is pretty nice that you decouple all of them.

My case thought is I want to follow the recommended-workflow (bump, write, commit, tag) but my commit messages are slight different from the preset "angular". 

So I created one config object which implements whatBump, writerOpts, parserOpts and would like to use it in the ```conventional-recommended-workflow``` package.

All the other packages ( bump, cli, core, etc ) accept this config object to override any preset configuration, but this recommended-flow don't.

I will open a PR so you can see better what I am saying =)
Thanks for the awesome work.

**Comment by bcoe** [comment]
@thiagofelix @stevemao we're probably going to delete this repo once we get more functionality merged with:

https://github.com/conventional-changelog/standard-changelog

I believe there are a few more configuration settings in this project already, however as @stevemao indicates; the idea as that this tool will be fairly opinionated (much like the standard style for code).

**Comment by thiagofelix** [comment]
@bcoe thanks for pointing.

I know it is opinionated, but it seems to be quite trivial to include the config option (given that downstream libs already accept config), it would allow much more flexibility =\ 

Or am I missing something?

**Comment by stevemao** [comment]
> it seems to be quite trivial

It is so not :) Please use https://github.com/conventional-changelog/conventional-changelog-cli :)

**Comment by bcoe** [comment]
@thiagofelix as soon as I land:

https://github.com/conventional-changelog/standard-version/pull/10/files

would you be willing to submit a pull request for the configuration settings you'd like to add, I'd happily land it.

**Comment by thiagofelix** [comment]
Sure. =)

**Comment by stevemao** [comment]
I'm not sure `conventional-recommended-bump` works well with `config`. Unless `config` includes `conventional-recommended-bump`'s `config` too.

**Comment by stevemao** [comment]
I came across https://github.com/conventional-changelog/conventional-changelog/pull/146, maybe the config could based on https://github.com/Jimdo/conventional-changelog-custom.

**Comment by bcoe** [comment]
@thiagofelix having ruminated on this a bit, I think I'm actually going to avoid accepting configuration for this module; taking a page from @feross' `standard`.

I'm actually about to make things slightly stricter, pulling in a slightly modified style-guide that fits my coworkers needs better at `npm` -- they're happy with the angular conventions, but @ceejbot would love to have the message length restriction lifted, I think this is worthwhile.

@thiagofelix I would love, however, for you to fork this library and make it fit whatever guidelines you have. This has worked great with modules like `semi-standard`:

https://github.com/Flet/semistandard

**Comment by thiagofelix** [comment]
Hi @bcoe, no problem.
I am already using a modified version that accept the config param for my daily job.

Thanks for the attention.
