### ISSUE TITLE
Review before commit

### ISSUE THREAD

**Issue by dignifiedquire** [conventional-changelog/standard-version#80]
It would be very nice if there was a way to review 
- the suggested version and 
- the changelog that was generated
  during the workflow and adjust them if needed. Currently I have to go back and squash fix commits or redo to whole thing. 

I imagine for the version it could be a nice interactive prompt telling you the version it will use and ask for either confirmation or a different version to be entered.

For the changelog it could work like `git commit` works, in that it opens the default `$EDITOR` and as soon as the file there is saved and closed it drops back into continuing the work.

**Comment by stvnwrgs** [comment]
Yeah, had the same issues, directly added it in #83. Sorry, that it's not in a seperate PR.

**Comment by bcoe** [comment]
@dignifiedquire sorry that it took so long! but this is now implemented with the flag `--dry-run`.
