### ISSUE TITLE
Rebuild CHANGELOG from begining

### ISSUE THREAD

**Issue by borisdamevin** [conventional-changelog/standard-version#812]
Hi, 

Do we have posibility to rebuild complete changelog from existing project for have full and clean `CHANGELOG.md`?

If not why?

Thank you.

**Comment by spattanaik75** [comment]
You should be able to do it. Here's the documentation:

```bash
# npm run script
npm run release -- --first-release
# global bin
standard-version --first-release
# npx
npx standard-version --first-release

```

Make sure you don't have any version tags in your repo. Otherwise it defaults to last tag. Default version tag format (vX.Y.Z)

**Comment by borisdamevin** [comment]
Hi @spattanaik75,

Is the point, I want rebuild all changelog from begining on repo with existing tags.

**Comment by pataar** [comment]
+1

**Comment by spattanaik75** [comment]
> 
> 
> Hi @spattanaik75,
> 
> Is the point, I want rebuild all changelog from begining on repo with existing tags.

Hi @borisdamevin 

If you don't have a tag with template "vX.Y.Z" format, then this should work right away. 
Can you advise what are the existing version tags in your repo. So that i can try and reproduce this scenario on my side. Tx

**Comment by borisdamevin** [comment]
Hi @spattanaik75 

The use case is just any repo with commits and any standard tags already register :) .

**Comment by spattanaik75** [comment]
if you want to create a changelog with existing commits (doesn't follow https://www.conventionalcommits.org/en/v1.0.0/) and version tags, then try https://github.com/conventional-changelog/conventional-changelog.
