### ISSUE TITLE
Command failed: git commit CHANGELOG.md - using as intended in gitlab CI

### ISSUE THREAD

**Issue by csi-lk** [conventional-changelog/standard-version#849]
**Describe the bug**
When running `yarn standard-version` in the node:16.12.0 docker container it fails with 

```
$ yarn standard-version
✔ outputting changes to CHANGELOG.md
✔ committing CHANGELOG.md
Command failed: git commit CHANGELOG.md -m chore(release): 1.1.0
Command failed: git commit CHANGELOG.md -m chore(release): 1.1.0
```

It looks like this is missing the quotes around the commit message?
Rolling back the version doesn't seem to help

Note: This is working fine locally which leads me to believe this is an environmental issue

**Environment**
- `standard-version` version(s): v9.3.2
- Node/npm version: node:16.12.0
- OS: Linux

**Comment by csi-lk** [comment]
After a ton of wasted time it looks like this is related to gitlab stripping quotes out on sub commands

related issue: https://gitlab.com/gitlab-org/gitlab-runner/-/issues/1742

**Comment by csi-lk** [comment]
Closing this as it seems to be a gitlab not `standard-version` issue, for anyone who comes across this I solved it by using `--skip.commit` and manually committing afterward in the CI

**Comment by tebaly** [comment]
This is BUG in version 8 and 9

Command failed: git commit CHANGELOG.md -m chore(release): ...

I downgrade to 4.2.* - and error gone
