### ISSUE TITLE
CHANGELOG generation bug

### ISSUE THREAD

**Issue by bcoe** [conventional-changelog/standard-version#85]
@stevemao, @Tapppi I ran into a frustrating CHANGELOG generation bug on two projects tonight:

https://github.com/atom/highlights/commit/1f8b248ab6bfe60a6d38599d3f00701dc062ab7f

and

https://github.com/istanbuljs/test-exclude/commit/c37f317d28442f98110e99046b50236cb44c2fbb

Usually things run like a charm, but in both these cases it aggressively started pulling in changes from the prior release -- any thoughts about what might be different about these two git histories?

**Comment by stevemao** [comment]
Looks like you didn't tag on the right commit. v2.1.0 doesn't tag on https://github.com/istanbuljs/test-exclude/commit/09f278870767f55bdb4ea7bfc37c17e140fe5ef9.

The commit chore(release): 2.1.0 cce8826 is deleted from the repo.

**Comment by Tapppi** [comment]
Both projects are missing the previous release from their commit history. If you look at the repo with something that can show branch graphs (e.g. SourceTree), you'll see that the previous tag (`2.1.0` or `1.4.0`) divert from the main branch. The changes from those commits appear to be in the next commit to the actual main branch, but the tags still point to diverting commits. So there is no previous release tag for `standard-version` to see. Don't really know how that happened to you though..

p.s. in the case of `atom/highlights` there is another commit https://github.com/atom/highlights@e9f40d8 that had its changes also rolled into the next commit https://github.com/atom/highlights@9cd8cb3.

**Comment by bcoe** [comment]
@Tapppi, @stevemao okay! that makes sense; I've been known to tag on a branch, and then release the branch to `next` rather than master -- so that folks can try out a candidate release.

Sounds like I would break the workflow if I don't pull onto master before doing this?

**Comment by stevemao** [comment]
You could run it on the branch you wanna release from.
