### ISSUE TITLE
How to run --release-as with npx

### ISSUE THREAD

**Issue by shinokada** [conventional-changelog/standard-version#894]
I tried the following to release as 0.3.3. However it released as 0.4.0.

How can I use `--release-as` with `npx`?

```sh
npx standard-version -- --release-as 0.3.3
Need to install the following packages:
  standard-version
Ok to proceed? (y) y
✔ bumping version in package.json from 0.3.3 to 0.4.0
✔ created CHANGELOG.md
✔ outputting changes to CHANGELOG.md
✔ committing package.json and CHANGELOG.md
✔ tagging release v0.4.0
ℹ Run `git push --follow-tags origin main && npm publish` to publish
```

**Comment by Nekolike** [comment]
Using npx, you need to omit the first two dashes. The following command should result in the proper version:

`npx standard-version --release-as 0.3.3`

**Comment by Nekolike** [comment]
Here's a comparison between the two commands:

<img width="436" alt="image" src="https://user-images.githubusercontent.com/22239854/158576574-bad7cc76-394f-4ee7-9357-21184e57241a.png">

<img width="434" alt="image" src="https://user-images.githubusercontent.com/22239854/158576609-e942d066-c3e6-4f51-83a8-e2551f71c74f.png">

**Comment by shinokada** [comment]
Thank you for the clarification.
