### ISSUE TITLE
Plan for Deno Support

### ISSUE THREAD

**Issue by jhechtf** [conventional-changelog/standard-version#895]
Greetings! I'm a frequent user of Deno, and was looking to see if there was a plan to allow for usage in Deno?

If not then I was planning on making a Deno compliant version.

**Comment by jhechtf** [comment]
I'll take the silence as a go-ahead to work on something in the Deno space. I'll make sure to credit standard-version for the inspiration.

**Comment by bcoe** [comment]
@jhechtf no plan to make a deno compliant version, actually just added a deprecation message to this project -- unfortunately there isn't time these days to work on standard-version in general.

Encourage you to work :+1:
