### ISSUE TITLE
Exit only on error code?

### ISSUE THREAD

**Issue by duclet** [conventional-changelog/standard-version#91]
So I have a post-commit hook which actually undo a commit if the history is not fully linear. Basically, it seems like any output that is made thru a commit hook, will end up on stderr. Since the code checks against that, it never gets to the tagging.

**Comment by stevemao** [comment]
> it seems like any output that is made thru a commit hook,

look like a bug in the commit hook

**Comment by Tapppi** [comment]
Idd, what are you using to create the commit-hook?

**Comment by duclet** [comment]
The problem isn't the hook itself. It seems like to me, all output from programs executed by the git hook forcefully redirect standard out to standard err. I've verify this by running the program directly and it outputs to stdout. When running from the githook, it redirects to stderr.

Perhaps my question is also on why it was decided to terminate execution when there is a message on stderr even though the exit code signals it is okay? In terms out logging and outputting messages, many programs I see can emit warnings (which generally goes to stderr), not just errors. When there is an error, it should be terminating with an exit code greater than 0.

**Comment by e-cloud** [comment]
[Source code here](https://github.com/conventional-changelog/standard-version/blob/master/index.js#L123)

One solution, when there is `null` err, and has stderr, the message may output as warnning and the program should not exit.

**Comment by nexdrew** [comment]
I agree with @duclet and @e-cloud - `standard-version` should not fail-fast simply from stderr output. I like the suggestion to "output a warning and continue". There's no reason to fail if git exits 0 (without an error).
