### ISSUE TITLE
Is it really deprecated forever and We should migrate to another solution?

### ISSUE THREAD

**Issue by tomavic** [conventional-changelog/standard-version#915]
Why there is no more information about the deprecation and more solutions as alternatives?

**Comment by techieshark** [comment]
https://github.com/conventional-changelog/standard-version/pull/907

**Comment by tomavic** [comment]
@TimothyJones Thanks for that. I will definitely try to `release-please` first on a sample app, and will check if it satisfies my needs.

For me I didn't find a solution yet to update my protected (`master` or `dev`) branches after each release on any `release/*` branch. I am allowing pipelines to force push of dev after each pre-release or release, so that `dev` branch is up-to-date with the latest commit all the time.

Any ideas on best way to do it without braking the rules of the protected branch? or any out-of-box idea on the whole workflow?

**Comment by TimothyJones** [comment]
It's a little off topic for this issue, but it's also an easy answer - the way release-please works is to separate the commit and the tag. It maintains a PR that contains the release commit and the current changelog. Once you merge the PR it tags the commit. It's a pretty clever solution.

**Comment by tomavic** [comment]
I am going to close the issue as it was an open discussion only. I hope it could help people coming from "Google Search Results" too 🤖
