### ISSUE TITLE
GitLab CI/CD pipeline + standard-version

### ISSUE THREAD

**Issue by dpergarc** [conventional-changelog/standard-version#936]
Hi there,

I am rather new with both GitLab CI/CD pipelines and standard-version, so forgive me beforehand if I am asking something that might be normal for many of you, or even has been discussed in other topics before.

I am trying to automatize the CHANGELOG.md procedure so as no one from the team has to execute commands by hand, but I am not sure what flowchart I have to follow, is anyone here able to give me some clues or some sort of guide?

I will share my current CI/CD .yml file (in txt format) just in case - I know it is wrong, it will generate an infinite loop of pipelines, I am seeking how to avoid that in first place.

[.gitlab-ci.txt](https://github.com/conventional-changelog/standard-version/files/11351808/default.gitlab-ci.txt)

Thank you for your time, sorry for the inconveniences, and looking forward to hearing from you.

Kind regards.
Daniel.

**Comment by brjadams** [comment]
@dpergarc - i think you are trying to get gitlab to skip triggering an infinite loop.
see: https://docs.gitlab.com/ee/user/project/push_options.html#push-options-for-gitlab-cicd

**Comment by dpergarc** [comment]
Hi there,

Thank you very much for your replies!! I managed to finish the task by following the next example I found on the Internet:
https://gitlab.com/felipe_public/felipe-kb-blog/versioning-example/-/blob/master/.gitlab-ci.yml

I also included the "skip procedure" as @brjadams suggested.

Again, thank you very much for your support.

Kind regards.
Daniel.
