### ISSUE TITLE
[question] Tags are not signed with GPG key

### ISSUE THREAD

**Issue by JaKXz** [conventional-changelog/standard-version#94]
As mentioned in gitter, I have found the tags I've been creating with `standard-version` are not being signed with my GPG key:

![screenshot 2016-08-22 20 05 24](https://cloud.githubusercontent.com/assets/2642545/17927299/003fad4e-69c3-11e6-8175-35f3c8827cf8.png)

**Comment by JaKXz** [comment]
...though I just noticed https://github.com/conventional-changelog/standard-version/blob/master/index.js#L144-L148 - I'm guessing I can fix this with `standard-version --sign`?

**Comment by stevemao** [comment]
@JaKXz why is this opened and closed? Mind asking questions at https://gitter.im/conventional-changelog/standard-version?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge?

**Comment by bcoe** [comment]
@JaKXz I thought we'd added something along these lines, but I don't see it in the README.md, perhaps open a separate issue to document this?

**Comment by JaKXz** [comment]
@stevemao I did ask there and there wasn't a response. I'll make a PR to more clearly document this, @bcoe you suggested it as I was typing :)
