### ISSUE TITLE
Can I use a Jira ticket number as a prefix to my commits

### ISSUE THREAD

**Issue by ismail-fathi** [conventional-changelog/standard-version#940]
I would like to have as a commit template is something like this:

`JiraTicketNumber | type(scope): commit subject` for example: `MT-230 | feat(PriceTag): add price modal`

By doing this will it affect by any means my changelog file or even block me for releasing a new tag?

thanks in advance 💯

**Comment by Regenhardt** [comment]
Probably won't work as expected. The standard is clear though, this is how you would format your example:

```
feat(PriceTag): add price modal

MT-230
```

There are also Jira-Integrations (for example for Gitlab) that pick up the ticket number and link the commit to the actual Jira ticket.

You could however fork this repository and implement your own format yourself.

**Comment by ismail-fathi** [comment]
Thanks @Regenhardt
