### ISSUE TITLE
Standard-version doesn't generate changelog correctly.

### ISSUE THREAD

**Issue by stevenKirill** [conventional-changelog/standard-version#947]
I try to generate changelog and I want to see only new commits in my new release, but instead I got all commits even from previous release, How can I tell the library to paste only new commits in my new release only after last tag ? Please help me

### Features

feat: created first component =>> don't need to paste it here
feat: created second component => only leave this as a new release in 1.20

### Bug Fixes =>> don't need to paste it here

* fix: fixed bug => don't need to paste it here

### Features

feat: created first component

### Bug Fixes

* fix: fixed bug

**Comment by felicioandre** [comment]
Hello @stevenKirill, can you see if [this answer](https://github.com/conventional-changelog/standard-version/issues/509#issuecomment-1690610700) can help you, please?

**Comment by stevenKirill** [comment]
Hi, I'm gonna try to use that discussion, thanks!
