### ISSUE TITLE
Ability to add other artifacts to the release commit

### ISSUE THREAD

**Issue by JaKXz** [conventional-changelog/standard-version#96]
ATM, I'm amending because I want the produced artifacts to be part of the `chore(release): x.x.x` commit.
```json
"prerelease": "webpack -p --bail", //produces some bundle artifacts that I want to commit
"release": "standard-version -s",
"postrelease": "git commit -a --amend --no-edit"
```

However, [because of the way git works](http://stackoverflow.com/a/3143658/1444541) this creates a new commit object since the original commit is tagged _before_ the amend happens. What would be nice is if my `postrelease` script was really a `poststandard-version` script (i.e. a "lifecycle-style" hook like the npm run script itself).

cc @stevemao @bcoe

**Comment by gkatsev** [comment]
Been looking at using standard-version for videojs. We basically do this for pre-build bundles for bower users or other users who don't want to use a bundler.
A potentially easy change is to be able to run the tagging portion of standard-version separately. So, you run the changelog generator, it doesn't commit or tag yet, then, you run your build script and then run the commit/tagging portion.
Or you could accept a command to run before committing. Kind of like you can do an `npm version` script that builds a release and adds the changes to git.

**Comment by JaKXz** [comment]
@bcoe @stevemao thanks for v3.0! :) do you guys have any thoughts on this though?

**Comment by bcoe** [comment]
@JaKXz I'm not opposed to this idea, would love to make sure we support a few common workflows; is there an approach that you think would work well for both your and @gkatsev's use-case?

**Comment by Tapppi** [comment]
@bcoe @gkatsev @JaKXz Is there still a need for a hook between `git add` and `git commit/tag`?  Does `v3.0` and `--commit-all` not enable this use case since artifacts built before the release script will be added to the commit?
```
"prerelease": "webpack -p --bail",
"release": "standard-version --commit-all" // Could replace --commit-all with -a
```
I'm not against supporting a "lifecycle-hook" between the add and commit/tag (e.g. `standard-version-pre-commit` or something less verbose) but at least this use case seems to be covered.

**Comment by gkatsev** [comment]
I think that `--commit-all` could potentially work for my usecase. It seems similar to what I've done with the built-in version script:
```
"version": "npm run build && git add -f dist/"
```
Then when npm's versioning runs, it just commits the entire thing.

**Comment by Tapppi** [comment]
Great! I think this issue can technically be closed, since you can commit any artifacts built before `standard-version` with `--commit-all`. Just gonna wait for @JaKXz to confirm that this works for him as well.

**Comment by Tapppi** [comment]
Actually we should keep this issue open to track documentation relating to this use-case.

**Comment by JaKXz** [comment]
@Tapppi `--commit-all` works! Thanks so much :D

**Comment by JaKXz** [comment]
...actually, I may have spoken too soon. I had to add the built assets to the release commit myself.

**Comment by JaKXz** [comment]
Based on https://github.com/conventional-changelog/standard-version/pull/121 it looks like I have to `git add .` before `standard-version -as`. 

Yes - documentation on this would be great, I can try to write something up tonight but can't promise free time so if someone else can do it please do

**Comment by Tapppi** [comment]
Yes, currently the commit-all flag just commits **already staged changes**. That might seem confusing, but I actually think it allows for greater control over the process. Needs to be clear in the documentation though. I'll take a look at the pr soon when I'm on my comp.
