### ISSUE TITLE
Deprecated package warnings for `q` and `stringify-package`

### ISSUE THREAD

**Issue by broofa** [conventional-changelog/standard-version#970]
When installing `standard-version`, users see the following warnings:
```bash
$ npm i standard-version
npm WARN deprecated stringify-package@1.0.1: This module is not used anymore, and has been replaced by @npmcli/package-json
npm WARN deprecated q@1.5.1: You or someone you depend on is using Q, the JavaScript Promise library that gave JavaScript developers strong feelings about promises. They can almost certainly migrate to the native JavaScript promise now. Thank you literally everyone for joining me in this bet against the odds. Be excellent to each other.

<...snip>
```

I believe the `q` dependency can be fixed by updating to a more recent version of `conventional-changelog`.  (`standard-version` is [three major versions behind that dependency](https://npmgraph.js.org/?q=standard-version#collapse=chalk%2Ccliui%2Cconventional-changelog-angular%2Cconventional-changelog-conventionalcommits%2Cconventional-changelog-core%2Cconventional-changelog-jquery%2Cconventional-changelog-jshint%2Cconventional-recommended-bump%2Cdotgitignore%2Cfigures%2Cfind-up%2Cgit-semver-tags%2Cstring-width%2Cstringify-package&select=exact%3Aconventional-changelog%403.1.25).

The `stringify-package` dependency is [directly declared by this module](https://npmgraph.js.org/?q=standard-version#collapse=chalk%2Ccliui%2Cconventional-changelog%2Cconventional-changelog-angular%2Cconventional-changelog-conventionalcommits%2Cconventional-changelog-core%2Cconventional-changelog-jquery%2Cconventional-changelog-jshint%2Cconventional-recommended-bump%2Cdotgitignore%2Cfigures%2Cfind-up%2Cgit-semver-tags%2Cstring-width%2Cyargs&select=exact%3Astringify-package%401.0.1), and should just be updated to `@npmcli/package-json` as described in the deprecation warning.

**Comment by dangreen** [comment]
@broofa Hi

1) standard-version use old conventional-changelog version
2) standard-version is deprecated

**Comment by broofa** [comment]
@dangreen  Ah... I didn't realize the project had been deprecated.

1. It would be helpful if someone could `npm deprecate standard-version` so the status of this project is a bit more obvoius.
2. You might consider putting this repository into "archive" mode since there's no intention to continue supporting it.  This would also make it a bit more obvious.

**Comment by TimothyJones** [comment]
It looks like only the most recent version isn’t deprecated (the npm deprecation message is what lead me to fork it two years ago). Not sure how that happened, but I agree it would be excellent if a maintainer could deprecate the more recent one too.
